### ISSUE TITLE
Vector query returns wrong elements

### ISSUE THREAD

**Issue by igrishaev** [igrishaev/etaoin#105]
```
(eta/wait-exists *chrome* [{:tag :a}
                               (bu/contains-text? "Download")])
```

```
(eta/click *chrome* [{:tag :a}
                         (bu/contains-text? "Download")])
```

```
This works:
```(eta/wait-exists *chrome* [{:tag :a}
                               (bu/contains-text? "Download")])
```
No exception, returns nil
However, this doesn’t work:

```(eta/click *chrome* [{:tag :a}
                         (bu/contains-text? "Download")])
```
When I click the `a` manually (in the Chrome window), the download starts.
Any idea?
This also works:
```(eta/visible? *chrome* [{:tag :a}
                            (bu/contains-text? "Download")])
```
The anchor is inside a modal, don’t know if that makes any difference.

igrishaev [3:08 PM]
@borkdude it’s probably because of a vector you are trying to find another element into a link. Try to use a single xpath selector
@borkdude smth like this: `".//a[(contains(text(), 'Download'))]"` (edited)
I’m not sure a vector-like query works 100% right

borkdude [3:10 PM]
yeah, that works…. question remains why `wait-exists` and `visible?` do work with that query though

igrishaev [3:12 PM]
I remember, `exists` does not really mean that an element is visible. But you can click on a visible element only. There might be more then one such links, so maybe you are selecting a wrong one.
try to use `wait-visible` instead of `wait-exists`
also, try to call `query-all` against this selector to ensure you really have only one result (edited)

borkdude [3:13 PM]
but `visible?` worked, so this is not relevant to this problem?
Trying…
Hmm, I get two back, you’re right

igrishaev [3:15 PM]
btw, is that a direct link without any javascript handlers? Because if so, there could be some tricky event that fires on not a link, or some other element.
oh great, try to decrease the scope of your selector then.

borkdude [3:17 PM]
it has a javascript handler
so `click` only clicks one element, not all selected elements? (edited)
I’m surprised that
```[{:tag :a}
                            (bu/contains-text? "Download")]
```
gives me two results. The other element was not or inside an `a` tag.

igrishaev [3:20 PM]
hm, that means a vector form of a query works not so well. I’ll create an issue for that. At the moment, try to pass just an Xpath expression.

borkdude [3:20 PM]
yes, thank you
fwiw, the other element was
```<h4 class="modal-title">Download citations</h4>```
```

**Comment by borkdude** [comment]
```
[{:tag :a}
 (bu/contains-text? "Download")]
```

evaluates to 

```
[{:tag :a} "//*[contains(text(),'Download')]"]
```

**Comment by borkdude** [comment]
Simplified test case:

HTML

```
<html>
  <body>
    <h1>Download</h1>
    <a>Download</a>
  </body>
</html>
```

Code:

```
(eta/go *chrome* "file:///private/tmp/test.html")
(eta/query-all *chrome* [{:tag :a}
                           "//*[contains(text(),'Download')]"])
```

This founds two elements where I think it should only find the anchor tag.

**Comment by igrishaev** [comment]
@borkdude great, that will help a lot.

**Comment by igrishaev** [comment]
@borkdude forgot to ask you, where does `(by/contains-text? ...)` come from? There is no such code in the library. Is it your code? What it does?

**Comment by igrishaev** [comment]
@borkdude is it just a wrapper that generates a string like `"//*[contains(text(),'Download')]"`, right?

**Comment by borkdude** [comment]
That's right. Just look at the simplified test case and ignore the rest.

**Comment by igrishaev** [comment]
@borkdude ok, I've found out what what the reason. When you pass a vector, each next query searches inside the previous one. Say, the first clause `{:tag :a}` returns an `a` element, and the next one `"//*[contains(text(),'Download')]"` tries to search inside that `a` you've just got back.

There are two mistakes here: first, the is nothing inside that `a` tag so the response should be empty. Second, you Xpath expression does not start with leading dot symbol: `.`. Without a dot, it means to search relative to the root of the document. That's why it finds `h1` tag.

If you put a dot at the beginning of Xpath, the result would be an empty vector, what is alright:

```
etaoin.api> (query-all driver [{:tag :a} ".//*[contains(text(),'Download')]"])
DEBUG etaoin.client: chrome 127.0.0.1:9515   POST session/c5d461825ddcef3dc62435bbdc76a185/element {:using "xpath", :value ".//a"}
DEBUG etaoin.client: chrome 127.0.0.1:9515   POST session/c5d461825ddcef3dc62435bbdc76a185/element/0.5929792826326579-1/elements {:using "xpath", :value ".//*[contains(text(),'Download')]"}
[]
```

You see, under the hood it performs to queries to the driver. But it's still is not what you want. To select that link with a single selector, use:

```
(query driver ".//a[contains(text(),'Download')]")
;; some element ID

(get-element-tag driver ".//a[contains(text(),'Download')]")
;; returns "a"

(click driver ".//a[contains(text(),'Download')]")
;; works fine
```

At the moment, I'm in the middle of rewriting query algorithms, I hope I'll simplify that and add a new section into readme.

**Comment by igrishaev** [comment]
@borkdude I added this case into readme: https://github.com/igrishaev/etaoin#querying-wrong-elements-with-xpath-expressions
