### ISSUE TITLE
etaoin/http-error

### ISSUE THREAD

**Issue by karishmakolli** [igrishaev/etaoin#113]
Not able to create a driver instance with chromedriver or geckodriver. Was working fine till couple days ago
chromedriver version - 2.35.528157
MacOS

error{:cause "throw+: {:response nil, :path \"session\", :payload {:desiredCapabilities {:loggingPrefs {:browser \"ALL\"}}}, :method :post, :type :etaoin/http-error, :port 3794, :host \"127.0.0.1\", :status 403, :driver {:type :chrome, :host \"127.0.0.1\", :port 3794, :url \"http://127.0.0.1:3794\", :locator \"xpath\", :capabilities {:loggingPrefs {:browser \"ALL\"}}, :args (\"chromedriver\" \"--port=3794\"), :env nil, :process #object[java.lang.UNIXProcess 0x51931fb1 \"java.lang.UNIXProcess@51931fb1\"]}}",
       :data {:response nil,
              :path "session",
              :payload {:desiredCapabilities {:loggingPrefs {:browser "ALL"}}},
              :method :post,
              :type :etaoin/http-error,
              :port 3794,
              :host "127.0.0.1",
              :status 403,
              :driver {:type :chrome,
                       :host "127.0.0.1",
                       :port 3794,
                       :url "http://127.0.0.1:3794",
                       :locator "xpath",
                       :capabilities {:loggingPrefs {:browser "ALL"}},
                       :args ("chromedriver" "--port=3794"),
                       :env nil,
                       :process #object[java.lang.UNIXProcess 0x51931fb1 "java.lang.UNIXProcess@51931fb1"]}},
       :via [{:type clojure.lang.Compiler$CompilerException,
              :message "clojure.lang.ExceptionInfo: throw+: {:response nil, :path \"session\", :payload {:desiredCapabilities {:loggingPrefs {:browser \"ALL\"}}}, :method :post, :type :etaoin/http-error, :port 3794, :host \"127.0.0.1\", :status 403, :driver {:type :chrome, :host \"127.0.0.1\", :port 3794, :url \"http://127.0.0.1:3794\", :locator \"xpath\", :capabilities {:loggingPrefs {:browser \"ALL\"}}, :args (\"chromedriver\" \"--port=3794\"), :env nil, :process #object[java.lang.UNIXProcess 0x51931fb1 \"java.lang.UNIXProcess@51931fb1\"]}} {:response nil, :path \"session\", :payload {:desiredCapabilities {:loggingPrefs {:browser \"ALL\"}}}, :method :post, :type :etaoin/http-error, :port 3794, :host \"127.0.0.1\", :status 403, :driver {:type :chrome, :host \"127.0.0.1\", :port 3794, :url \"http://127.0.0.1:3794\", :locator \"xpath\", :capabilities {:loggingPrefs {:browser \"ALL\"}}, :args (\"chromedriver\" \"--port=3794\"), :env nil, :process #object[java.lang.UNIXProcess 0x51931fb1 \"java.lang.UNIXProcess@51931fb1\"]}}, compiling:(form-init3490550857094851676.clj:1:13)",
              :at [clojure.lang.Compiler$InvokeExpr eval "Compiler.java" 3657]}
             {:type clojure.lang.ExceptionInfo,
              :message "throw+: {:response nil, :path \"session\", :payload {:desiredCapabilities {:loggingPrefs {:browser \"ALL\"}}}, :method :post, :type :etaoin/http-error, :port 3794, :host \"127.0.0.1\", :status 403, :driver {:type :chrome, :host \"127.0.0.1\", :port 3794, :url \"http://127.0.0.1:3794\", :locator \"xpath\", :capabilities {:loggingPrefs {:browser \"ALL\"}}, :args (\"chromedriver\" \"--port=3794\"), :env nil, :process #object[java.lang.UNIXProcess 0x51931fb1 \"java.lang.UNIXProcess@51931fb1\"]}}",
              :data {:response nil,
                     :path "session",
                     :payload {:desiredCapabilities {:loggingPrefs {:browser "ALL"}}},
                     :method :post,
                     :type :etaoin/http-error,
                     :port 3794,
                     :host "127.0.0.1",
                     :status 403,
                     :driver {:type :chrome,
                              :host "127.0.0.1",
                              :port 3794,
                              :url "http://127.0.0.1:3794",
                              :locator "xpath",
                              :capabilities {:loggingPrefs {:browser "ALL"}},
                              :args ("chromedriver" "--port=3794"),
                              :env nil,
                              :process #object[java.lang.UNIXProcess 0x51931fb1 "java.lang.UNIXProcess@51931fb1"]}},
              :at [slingshot.support$stack_trace invoke "support.clj" 201]}],
       :trace [[slingshot.support$stack_trace invoke "support.clj" 201]
               [etaoin.client$call invokeStatic "client.clj" 97]
               [etaoin.client$call invoke "client.clj" 64]
               [etaoin.api$create_session invokeStatic "api.clj" 141]
               [etaoin.api$create_session doInvoke "api.clj" 135]
               [clojure.lang.RestFn invoke "RestFn.java" 423]
               [etaoin.api$connect_driver invokeStatic "api.clj" 2629]
               [etaoin.api$connect_driver doInvoke "api.clj" 2606]
               [clojure.lang.RestFn invoke "RestFn.java" 423]
               [etaoin.api$boot_driver invokeStatic "api.clj" 2666]
               [etaoin.api$boot_driver doInvoke "api.clj" 2652]
               [clojure.lang.RestFn invoke "RestFn.java" 410]
               [clojure.core$partial$fn__4759 invoke "core.clj" 2514]
               [clojure.lang.AFn applyToHelper "AFn.java" 152]
               [clojure.lang.RestFn applyTo "RestFn.java" 132]
               [clojure.lang.Compiler$InvokeExpr eval "Compiler.java" 3652]
               [clojure.lang.Compiler$DefExpr eval "Compiler.java" 451]
               [clojure.lang.Compiler eval "Compiler.java" 6932]
               [clojure.lang.Compiler eval "Compiler.java" 6890]
               [clojure.core$eval invokeStatic "core.clj" 3105]
               [clojure.core$eval invoke "core.clj" 3101]
               [clojure.main$repl$read_eval_print__7408$fn__7411 invoke "main.clj" 240]
               [clojure.main$repl$read_eval_print__7408 invoke "main.clj" 240]
               [clojure.main$repl$fn__7417 invoke "main.clj" 258]
               [clojure.main$repl invokeStatic "main.clj" 258]
               [clojure.main$repl doInvoke "main.clj" 174]
               [clojure.lang.RestFn invoke "RestFn.java" 1523]
               [clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__672 invoke "interruptible_eval.clj" 87]
               [clojure.lang.AFn applyToHelper "AFn.java" 152]
               [clojure.lang.AFn applyTo "AFn.java" 144]
               [clojure.core$apply invokeStatic "core.clj" 646]
               [clojure.core$with_bindings_STAR_ invokeStatic "core.clj" 1881]
               [clojure.core$with_bindings_STAR_ doInvoke "core.clj" 1881]
               [clojure.lang.RestFn invoke "RestFn.java" 425]
               [clojure.tools.nrepl.middleware.interruptible_eval$evaluate invokeStatic "interruptible_eval.clj" 85]
               [clojure.tools.nrepl.middleware.interruptible_eval$evaluate invoke "interruptible_eval.clj" 55]
               [clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__717$fn__720
                invoke
                "interruptible_eval.clj"
                222]
               [clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__712 invoke "interruptible_eval.clj" 190]
               [clojure.lang.AFn run "AFn.java" 22]
               [java.util.concurrent.ThreadPoolExecutor runWorker "ThreadPoolExecutor.java" 1149]
               [java.util.concurrent.ThreadPoolExecutor$Worker run "ThreadPoolExecutor.java" 624]
               [java.lang.Thread run "Thread.java" 748]]}

**Comment by igrishaev** [comment]
Probably you have an app that already runs on that port.
```
pkill chromedriver
pkill geckodriver
```

**Comment by karishmakolli** [comment]
Hi Ivan,

Thanks for the quick response.
I have killed all the process and made sure the ports are available but I
still get the same error.

Thanks
Karishma

**Comment by igrishaev** [comment]
Karishma, there is something wrong with your local installation. Let me think more on how to get thw whole logs.

**Comment by karishmakolli** [comment]
Ivan, Though these may help you de-bug. 
I tried (create-driver) (run-driver) (connect-driver) and (create-session) individually and below are the responses.

(use 'etaoin.api)
(require '[etaoin.keys :as k])
=> nil
=> nil
(def driv (create-driver :chrome))
=> #'user/driv
driv
=>
#object[clojure.lang.Atom
        0x6dc4776c
        {:status :ready,
         :val {:type :chrome, :host "127.0.0.1", :port 9515, :url "http://127.0.0.1:9515", :locator "xpath"}}]
(run-driver driv)
=>
#object[clojure.lang.Atom
        0x6dc4776c
        {:status :ready,
         :val {:type :chrome,
               :host "127.0.0.1",
               :port 9515,
               :url "http://127.0.0.1:9515",
               :locator "xpath",
               :capabilities {:loggingPrefs {:browser "ALL"}},
               :args ("chromedriver" "--port=9515"),
               :env nil,
               :process #object[java.lang.UNIXProcess 0x625430e5 "java.lang.UNIXProcess@625430e5"]}}]
(connect-driver driv)
ExceptionInfo throw+: {:response nil, :path "session", :payload {:desiredCapabilities {:loggingPrefs {:browser "ALL"}}}, :method :post, :type :etaoin/http-error, :port 9515, :host "127.0.0.1", :status 403, :driver {:type :chrome, :host "127.0.0.1", :port 9515, :url "http://127.0.0.1:9515", :locator "xpath", :capabilities {:loggingPrefs {:browser "ALL"}}, :args ("chromedriver" "--port=9515"), :env nil, :process #object[java.lang.UNIXProcess 0x625430e5 "java.lang.UNIXProcess@625430e5"]}}  slingshot.support/stack-trace (support.clj:201)

(create-session driv)
ExceptionInfo throw+: {:response nil, :path "session", :payload {:desiredCapabilities {}}, :method :post, :type :etaoin/http-error, :port 9515, :host "127.0.0.1", :status 403, :driver {:type :chrome, :host "127.0.0.1", :port 9515, :url "http://127.0.0.1:9515", :locator "xpath", :capabilities {:loggingPrefs {:browser "ALL"}}, :args ("chromedriver" "--port=9515"), :env nil, :process #object[java.lang.UNIXProcess 0x625430e5 "java.lang.UNIXProcess@625430e5"]}}  slingshot.support/stack-trace (support.clj:201)

**Comment by karishmakolli** [comment]
Ivan,

I had a proxy setting set for other API project and it was redirecting the HTTP call. after disabling the proxy I am able to use the driver. Thank you so much for your time!

**Comment by igrishaev** [comment]
@karishmakolli you are welcome!

Next time, try to use just `(def driver (chrome))` rather then calling those three functions in series.
