### ISSUE TITLE
query children of element 

### ISSUE THREAD

**Issue by Atsman** [igrishaev/etaoin#139]
How to query children of element?

**Comment by spieden** [comment]
Here's what I came up with:

```clojure
(defn query-under [driver ancestor-el descendant-q]
  (let [[loc term] (etaoin.query/expand driver descendant-q)]
    (etaoin.api/find-element-from* driver ancestor-el loc term)))
```

**Comment by Atsman** [comment]
@igrishaev can you add it to the core?

**Comment by igrishaev** [comment]
Sorry for the delay, let me think on that a bit.

**Comment by Atsman** [comment]
@igrishaev ??

**Comment by igrishaev** [comment]
@Atsman sorry for the delay again, these days are full of my ordinary work. Did you try to use a vector form as it's described in the readme file? https://github.com/igrishaev/etaoin#vector-syntax-for-querying

```clojure
(click driver [{:tag :html} {:tag :body} {:tag :a}])
```

In the example above, you find the html tag, them the body inside it, then the first link on the body. Could you provide you example please?

**Comment by Atsman** [comment]
My use case is to take a list of elements, iterate through them and find in each of element some children. Most of the tools have such API. So the same as @spieden use case.

How can I use vector API? Can I place an element as the first element of vector?
