### ISSUE TITLE
Driver start hangs if port is in use

### ISSUE THREAD

**Issue by stuartsierra** [igrishaev/etaoin#14]
If the port used for communication with the webdriver is already in use by another process, starting a driver blocks forever.

## Steps to reproduce

Use `[etaoin "0.1.5"]`, which uses 5555 as the default port for chromedriver

Start a server process listening on port 5555. One way to do this is to start Clojure with the Java command-line option:

    "-Dclojure.server.repl={:port 5555 :accept clojure.core.server/repl}"

Alternatively, Netcat can run a server like this:

    nc -kl 127.0.0.1 5555

At the Clojure REPL, run:

    (require '[etaoin.api :as e])
    (def c (e/chrome))

The REPL blocks and does not return.

## Notes

Running Netcat, I can see the HTTP request to start the webdriver session:

```
$ nc -kl 127.0.0.1 5555
POST /session HTTP/1.1
Connection: close
content-type: application/json
accept: application/json
accept-encoding: gzip, deflate
Content-Length: 26
Host: 127.0.0.1:5555
User-Agent: Apache-HttpClient/4.5.2 (Java/1.8.0_92)

{"desiredCapabilities":{}}
```

If I kill the Netcat process, `org.apache.http.NoHttpResponseException` is thrown in the REPL. Otherwise, the REPL just hangs forever.

## Possible resolutions

Adding a timeout on the HTTP response would at least provide some indication of a problem, although it would not necessarily help with diagnosis.

For greater robustness, it would be ideal to find an unused port.

**Comment by igrishaev** [comment]
Many thanks for such detailed report! Will take a look soon.

**Comment by igrishaev** [comment]
Fixed in 0a2c61c4f691555c9b77ec3bb871d50b4037deb7
Available in a new snapshot (deployed to Clojars).
Now it tries to find a non-used port. Does it work for you?

**Comment by igrishaev** [comment]
@stuartsierra 
Fixed a bit more, fill free to use the latest `[etaoin "0.1.5-SNAPSHOT"]`

**Comment by stuartsierra** [comment]
This appears to protect against choosing a port that's in use.

**Comment by igrishaev** [comment]
Great, closing.
