### ISSUE TITLE
make timeout configurable

### ISSUE THREAD

**Issue by behrica** [igrishaev/etaoin#142]
I have a test, which tests a button which creates a cvs file and downloads it.
This request takes typically more tehn 5 minutes, so the timeout in client.clj of 60 seconds is far to low.

I think it should be configurable

**Comment by kennethkalmer** [comment]
I've got a similar issue in CI where the machine is under a lot of stress and I get periodic false negatives. Undoubtedly my code needs a lot of work as well to just be faster... I do however depend heavily on the tests, slow or not.

**Comment by Atsman** [comment]
The easiest way to solve it in the current code base is to read it from env variables. It is super easy to implement. Please check https://github.com/igrishaev/etaoin/pull/152

**Comment by igrishaev** [comment]
solved
