### ISSUE TITLE
Vector query syntax only queries the first result of the previous query

### ISSUE THREAD

**Issue by deadghost** [igrishaev/etaoin#143]
```
;; [etaoin "0.2.8"]
(def driver (chrome))
(go driver "https://contactful.co/")
(query-all driver [{:class "slide"}]) ; => ["0.061420485825728566-1" "0.061420485825728566-2" "0.061420485825728566-3"]
;; Each one of the results in the previous query contain a :h2
(query-all driver [{:class "slide"} {:tag :h2}]) ; => ["0.061420485825728566-4"]
;; We only got the :h2 for the first result
```

I expected it to return a vector containing the `:h2` of every `:.slide`.

**Comment by igrishaev** [comment]
yes, you're right: every next form takes into account only the first result from the previous one. There might be an experimental `query-tree` function that acts like you proposed

**Comment by igrishaev** [comment]
@Uunnamed 

create a function that takes a vector of selectors and acts like a tree. 

```
[{:tag :div} {:tag :a}]
```

means

```
{:tag :div} -> [div1 div2 div3]

div1 -> [a1 a2 a3]
div2 -> [a4 a5 a6]
div3 -> [a7 a8 a9]
```

so the result will be `[a1 ... a9]`

**Comment by igrishaev** [comment]
it would be nice to have a reduce function that takes a layer after layer and accumulates the vector of elements. In each step, it queries elements from the previous step.

**Comment by Uunnamed** [comment]
Hi @deadghost 
Since etaoin 0.3.9 for this purpose will available function `query-tree`
