### ISSUE TITLE
HTTP_PROXY

### ISSUE THREAD

**Issue by igrishaev** [igrishaev/etaoin#148]

**Comment by igrishaev** [comment]
add a function and examples in readme

**Comment by saleepeppe** [comment]
Is there any update here? Can I help? 
I have no clue on how to approach this issue but it would be a useful feature.

**Comment by igrishaev** [comment]
@saleepeppe could you please remind me what was meant by that issue? To handle the HTTP proxy settings from the environment?

**Comment by igrishaev** [comment]
As I understand, the task is about to handle HTTP(S)_PROXY env variable (or http(s)_proxy) and then apply it to clj-http. Add example to readme and upate the ToC. Also, would be nice to test it against a real proxy (either local or a public one).

**Comment by igrishaev** [comment]
No, I was wrong: we need to set proxy for a browser.

- consider using the `:proxy` key for the driver. The key may be either a string or a pair of host/port
- also take into account `HTTP(S)_PROXY` env var;
- when one of above is set, add proxy to the browser. For this, dive into Selenium sources to discover what is behind this for each driver. For example: https://chromedriver.chromium.org/capabilities
- Add examples in readme
- the best place for this would be the `etaoin.driver` namespace (see examples from there).

**Comment by igrishaev** [comment]
```clojure
{:proxy {:http "http://some.proxy.com:8080"
         :ftp "ftp:/...."
         :ssl "https:/...."
         :socks "......."
         :socks-version 5
         :bypass ["http://this.url" "http://that.rul"]}}
```

**Comment by igrishaev** [comment]
With any of these keys, the proxyType is set to "manual" automatically.

**Comment by igrishaev** [comment]
```
{:proxy {:pac-url "http://..."}}
```

With that option, the proxyType turns into "pac"

**Comment by igrishaev** [comment]
use cond-> to build a W3C object out from our proxy configuration.

**Comment by igrishaev** [comment]
when HTTP_PROXY is set, add http proxy to our config. Do the same for HTTPS_PROXY (ssl)

**Comment by igrishaev** [comment]
In readme, add examples for our proxy config and for manual W3c config in capabilites.

**Comment by igrishaev** [comment]
- user-friendly configuration: we build a w3c object and push it into capabilities
```
(chrome {:proxy {}})
```

- manual w3c configuration, we do nothing:
```
(chrome {:capabilities {:proxy {}})
```

**Comment by igrishaev** [comment]
```
:socks {:host "..." :version 5}
```
