### ISSUE TITLE
Internal design api

### ISSUE THREAD

**Issue by Atsman** [igrishaev/etaoin#149]
In my opinion, such API is not good, very hard to read and to reason about. I would suggest to pass map as parameter to this macro, instread of having 5 arguments.

https://github.com/igrishaev/etaoin/blob/e0f8aa83520a1fcc39de951215c976cd382e5aa5/src/etaoin/api.clj#L107

When you open codebase and see that call, it's impossible to say what does nil and _ mean, what other arguments mean. 
```clojure
(defmethods double-click-el
  [:chrome :phantom]
  [driver el]
  (with-resp driver :post
    [:session (:session @driver) :element el :doubleclick]
    nil _))
```

Will became:

```clojure
(defmethods double-click-el
  [:chrome :phantom]
  [driver el]
  (with-resp {:driver driver 
              :method :post
              :path [:session (:session @driver) :element el :doubleclick]))
```

And that code is much easier to read and there is not null or _ arguments.

If you agree then i can refactor it myself and send a pull request.

**Comment by gadfly361** [comment]
@Atsman I think that is a good point, and I also like using maps as inputs when the argument list gets long.

As an aside, I would encourage all of us to speak more neutrally when opening an issue on an open source project.

**Comment by Atsman** [comment]
@gadfly361 sure, I apologize, changed text.

**Comment by igrishaev** [comment]
@Atsman thank you for your feedback. At the moment, I don't see a reason to change the internal API. `with-resp` is a macro and thus takes not a map but a strict set of parameters. Once you start to fix the old version to a new one you'll see there are lots of places should be changed.

**Comment by Atsman** [comment]
@igrishaev is there a rule that macro should take raw params instead of map? I don't think so.

```clojure
(defmacro with-resp [{:keys [driver method path data result]} & body]
`(let [~result (client/call ~driver
                              ~method
                              ~path
                              ~data)]
     ~@body)
```

I would even say that decision to have such macro is questionable, i don't see any reason for that. I would use just a function. Because you just use result somehow.

Example - current way:

```clojure
(defmethods get-active-element*
  [:chrome :phantom :safari]
  [driver]
  (with-resp driver :post
    [:session (:session @driver) :element :active]
    nil resp
    (-> resp :value :ELEMENT)))
```

What i would like to see:

```clojure
(defmethods get-active-element*
  [:chrome :phantom :safari]
  [driver]
  (-> (with-resp {:driver driver 
                  :method :post
                  :path [:session (:session @driver) :element :active])
      :value 
      :ELEMENT)
```

In my opinion much more readable, much more clean, much more easier to reason about.
Because what rule i am sure exists in clojure world is don't use macros just to use macros.

**Comment by Atsman** [comment]
I just checked it is around 100 places to change. I think it is not so hard, I can do it my self, it is not a big price to pay to make the project better! In general, I love this project and just want to make it even better!

**Comment by Atsman** [comment]
@gadfly361 hey, what is your's opinion? Can u please review https://github.com/igrishaev/etaoin/pull/150

**Comment by igrishaev** [comment]
Closing as related to #150 which is fixed.
