### ISSUE TITLE
maximize for chrome

### ISSUE THREAD

**Issue by igrishaev** [igrishaev/etaoin#15]
Recently, maximize started to rise an exception in the latest chrome.

**Comment by igrishaev** [comment]
chromedriver issue; added to wiki.

**Comment by jtackett** [comment]
We should reopen this issue. Maximizing a chrome window, then calling (go...) results in an error:

```
(def d (maximize (chrome {:download-dir <download-dir>}))
(go d "google.com")
```

**Error Stack**
java.lang.ClassCastException: clojure.lang.PersistentArrayMap cannot be cast to java.util.concurrent.Future
            core.clj:2206 clojure.core/deref-future
            core.clj:2228 clojure.core/deref
            core.clj:2214 clojure.core/deref
              api.clj:363 etaoin.api/go
              api.clj:352 etaoin.api/go
/Users/jtackett/Desktop/Foodbam/skyscraper/src/skyscraper/scrape/engine.clj:350 skyscraper.scrape.engine/eval23708
/Users/jtackett/Desktop/Foodbam/skyscraper/src/skyscraper/scrape/engine.clj:350 skyscraper.scrape.engine/eval23708
       Compiler.java:6927 clojure.lang.Compiler.eval
       Compiler.java:6890 clojure.lang.Compiler.eval
            core.clj:3105 clojure.core/eval
            core.clj:3101 clojure.core/eval
              eval.clj:79 lighttable.nrepl.eval/->result
              eval.clj:76 lighttable.nrepl.eval/->result
            core.clj:2515 clojure.core/partial[fn]
            core.clj:2644 clojure.core/map[fn]
          LazySeq.java:40 clojure.lang.LazySeq.sval
          LazySeq.java:49 clojure.lang.LazySeq.seq
              RT.java:521 clojure.lang.RT.seq
             core.clj:137 clojure.core/seq
            core.clj:2700 clojure.core/filter[fn]
          LazySeq.java:40 clojure.lang.LazySeq.sval
          LazySeq.java:49 clojure.lang.LazySeq.seq
              RT.java:521 clojure.lang.RT.seq
             core.clj:137 clojure.core/seq
            core.clj:3024 clojure.core/dorun
            core.clj:3039 clojure.core/doall
            core.clj:3039 clojure.core/doall
             eval.clj:128 lighttable.nrepl.eval/eval-clj
             eval.clj:127 lighttable.nrepl.eval/eval-clj
          RestFn.java:442 clojure.lang.RestFn.invoke
             eval.clj:189 lighttable.nrepl.eval/eval2495[fn]
             AFn.java:152 clojure.lang.AFn.applyToHelper
             AFn.java:144 clojure.lang.AFn.applyTo
             core.clj:646 clojure.core/apply
            core.clj:1881 clojure.core/with-bindings*
            core.clj:1881 clojure.core/with-bindings*
          RestFn.java:425 clojure.lang.RestFn.invoke
             eval.clj:179 lighttable.nrepl.eval/eval2495[fn]
             eval.clj:178 lighttable.nrepl.eval/eval2495[fn]
         MultiFn.java:229 clojure.lang.MultiFn.invoke
              core.clj:86 lighttable.nrepl.core/queued[fn]
            core.clj:2459 clojure.core/comp[fn]
interruptible_eval.clj:159 clojure.tools.nrepl.middleware.interruptible-eval/run-next[fn]
              AFn.java:22 clojure.lang.AFn.run
ThreadPoolExecutor.java:1149 java.util.concurrent.ThreadPoolExecutor.runWorker
ThreadPoolExecutor.java:624 java.util.concurrent.ThreadPoolExecutor$Worker.run
          Thread.java:748 java.lang.Thread.run
