### ISSUE TITLE
Query use not clear

### ISSUE THREAD

**Issue by alanmarazzi** [igrishaev/etaoin#153]
Hi! I'm loving **Etaoin**, but I don't understand how am I supposed to use `query` and `query-all`. I was guessing I could query elements and then pass the result to `click`, `fill` or similar, but it looks like that doesn't work.

Are `query` and `query-all` supposed to work like this or they are just for checking whether there is something in the page?

**Comment by mgerlach-klick** [comment]
I ran into this yesterday. `query` is what converts the query data structure (e.g. `{:css "#foo"}`) into the element (id?) that etaoin actually uses. To interact with these elements, you have to pass it to different functions, namely `click-el`, `fill-el`, etc.

**Comment by alanmarazzi** [comment]
Thank you very much!!! It seemed weird I couldn't do something like this.

I'll try it ASAP and if it's interesting I could add a couple of examples to the README

**Comment by mgerlach-klick** [comment]
Some more explanation in the readme would be nice. This stumped me for a good bit yesterday, especially since `query-all` was the only workaround for #154

**Comment by Atsman** [comment]
@alanmarazzi in my opinion public api functions should accept both selectors and elements. Because it is super weird that we as clients of that api have to care about both click and click-el.

We can create multi methods or something to make it much more usable.

**Comment by alanmarazzi** [comment]
Since we are dealing with types aren't protocols the best practice (I'm really asking, I'm not yet an expert at these things)? Though I should take a deeper look to `click` and `fill` implementation.
