### ISSUE TITLE
User defaults for default-timeout default-interval default-locator

### ISSUE THREAD

**Issue by snoe** [igrishaev/etaoin#160]
It would be nice if it was possible for user code to be able to specify their own `default-*` values in the api. This could probably be done with `^:dynamic` vars.

As it stands a 30 second timeout is too long for our particular use case and it would be nice not to have pass in opts to all the wait api calls.

**Comment by igrishaev** [comment]
agree, we'll take this in work

**Comment by igrishaev** [comment]
@Uunnamed create global dynamic vars and some macros like `(with-locator ...)`, `(with-wait-timeout)` etc. Add to readme

**Comment by igrishaev** [comment]
@snoe We've added the `with-wait-timeout` and `with-wait-interval` macros, they will be in the release soon.
