### ISSUE TITLE
Fix failing tests.

### ISSUE THREAD

**Issue by atsman** [igrishaev/etaoin#162]
https://circleci.com/gh/marco-m/etaoin/36

**Comment by marco-m** [comment]
Now it is https://circleci.com/gh/igrishaev/etaoin, yes! :-)

Was your PR that removed the crash in the fixture in the firefox tests ? Now both Firefox and non-Firefox tests run to completion.

**Comment by Atsman** [comment]
@marco-m i am not sure. Will it automatically test PRs now ?

**Comment by igrishaev** [comment]
@Atsman it should build. Let me know if it not.

**Comment by marco-m** [comment]
If @igrishaev enabled building of PRs, yes. Unfortunately wether a project has this feature enabled or not is visible only to the project owner. We will know on the first PR :-) 

If you look at my new PR #169, situation is unclear. My interpretation is the following: CircleCI detected that my own fork has CI enabled, so it used that to validate the PR. Still it is not clear if upstream has build PR enabled or not.

**Comment by marco-m** [comment]
Yes it is setup correctly, see screenshot in #164

**Comment by igrishaev** [comment]
@Uunnamed I believe this one can be closes as our tests are green now?

**Comment by Uunnamed** [comment]
@igrishaev yep.
