### ISSUE TITLE
create account on CircleCI

### ISSUE THREAD

**Issue by marco-m** [igrishaev/etaoin#164]
@igrishaev, to be sure you don't forget. From the PR who added CicleCI support, you need to

1. create project on circleci. You can login using github auth and follow the instructions, it should be straightforward. It is impossible for somebody else to do it i think, although you game me commit access to the repo, you are the owner and you have to login as yourself.
2. enable building for PR
3. update README.md to point to the correct etaoin on circleci :-)

**Comment by igrishaev** [comment]
I've created and set up the account, could you check if everything is alright please?

**Comment by marco-m** [comment]
Hello Ivan,
from what I can see logged in as myself, it is setup correctly. Did you also enabled builds for Pull Requests ? That would be cool.

The build is read because there are 6 failures and 1 error. If you have a look, now both the FIrefox test run and the non-Firefox test run don't crash. When I submitted the PR to add CircleCI support, the tests with Firefox would crash due to an exception in the fixture code, so now the situation has improved!

**Comment by igrishaev** [comment]
Marco, the build settings are the following. It seems that all the
commits/PRs should be built.

**Comment by igrishaev** [comment]
![screencapture-circleci-gh-igrishaev-etaoin-edit-2018-08-07-17_10_27](https://user-images.githubusercontent.com/1059232/43781236-2386c02e-9a65-11e8-8f62-a394e9a51010.png)

**Comment by marco-m** [comment]
yes, it is setup correctly, "Build forked pull requests", good!
