### ISSUE TITLE
Can't download files in headless Chrome

### ISSUE THREAD

**Issue by olfal** [igrishaev/etaoin#170]
Hi,

As you probably know, you cannot directly download a file in headless Chrome by going to a URL, as it's disabled by default. When using the `go` function and providing a download URL, it will silently fail.

Based on [this Chromium issue](https://bugs.chromium.org/p/chromedriver/issues/detail?id=1973#c21), we should be able to allow the download behavior by setting `Page.setDownloadBehavior` to `{ behavior: 'allow', downloadPath: "./" }` in the driver.

Any idea if it is possible to set this download behavior using etaoin?

Thanks for your time!

**Comment by olfal** [comment]
I was able to achieve that with the following code : 
```clojure
(etaoin/with-resp driver
                  :post
                  [:session (:session @driver) "chromium/send_command"]
                  {:cmd    "Page.setDownloadBehavior"
                   :params {:behavior     "allow"
                            :downloadPath download-directory}}
                  _)
```

**Comment by suryaaditya** [comment]
etaoin/with-resp is from earlier versions. do you have something working with the latest code? I could not get it to work. thanks.
