### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by piotr-yuxuan** [igrishaev/etaoin#172]
Hello! Whilst authoring PR https://github.com/igrishaev/etaoin/pull/171 I've noticed there have been quite a few changes in the internals between current latest release (from February) and actual `HEAD`, for example:

``` diff
-(defn get-element-tag-el
-  "Returns element's tag name by its identifier."
-  [driver el]
-  (:value (execute {:driver driver
-                    :method :get
-                    :path [:session (:session @driver) :element el :name]})))
+(defn get-element-tag-el
+  "Returns element's tag name by its identifier."
+  [driver el]
+  (with-resp driver :get
+    [:session (:session @driver) :element el :name]
+    nil
+    resp
+    (:value resp)))
```

Do you think it would justify a new release? even if it's beta, I believe it would be helpful to keep track of changes and intents behind them.

By the way, why getting rid of such macro?

**Comment by mgerlach-klick** [comment]
Yes, please! I need `get-element-inner-html-el` :)

**Comment by igrishaev** [comment]
Done. Check out `[etaoin "0.2.9"]` please.
