### ISSUE TITLE
dir is not created in postmortem handler

### ISSUE THREAD

**Issue by hukka** [igrishaev/etaoin#180]
Docs of with-postmortem say that `:dir`"Might not exist, will be created otherwise", but if the dir hasn't been created manually beforehand, etaoin will fail with java.io.FileNotFoundException: No such file or directory.

Not sure if docs need to clarify this, or if this is missing functionality.

**Comment by anthonygalea** [comment]
I think this can be closed. Seems it was fixed in 12e33cf. Can you confirm @hukka?

**Comment by Macroz** [comment]
I can have a look at it.

Furthermore, there is the issue that at least I want to empty that directory on every run. So maybe we'll have to have some custom magic in the fixture anyway.

**Comment by Uunnamed** [comment]
@hukka fixed
