### ISSUE TITLE
[chrome] Accessing any element after /go waits for the whole page to load

### ISSUE THREAD

**Issue by marceloramires** [igrishaev/etaoin#185]
I'm using a headless chrome driver instance, and running:

`(etaoin/go driver <url>)`

this line takes as long as the page takes to load in its entirety. I want an element that appears really quickly, so I tried doing this:

```
(future (etaoin/go driver <url>))
(etaoin/wait-visible driver {:xpath <xpath>})
```

And even though now the first line is instant, running /go on a separate thread, the second one waits not only for the element I'm querying, but for the whole page. Then I tried accessing the element directly:

```
(future (etaoin/go driver <url>))
(etaoin/get-element-inner-html driver {:xpath <xpath>})
```

And the second line waits for the whole page to load too, and then gives me the correct value.

I searched and webdriver allows querying before the page is entirely loaded. Is it possible to do this with etaoin?

**Comment by marceloramires** [comment]
@igrishaev take a look? :)

**Comment by igrishaev** [comment]
Done, please install the new `[etaoin "0.3.0"]` version and check the readme file (section "eager page load")

A quick example:

```clojure
(def c (chrome {:load-strategy :none}))
(go c "http://some.slow.site.com")
;; no pause, acts immediately
(do-something)
```

**Comment by marceloramires** [comment]
Thank you very much! I can confirm that it works! =)
