### ISSUE TITLE
get-element-inner-html fails on phantomjs

### ISSUE THREAD

**Issue by ejschoen** [igrishaev/etaoin#186]
This might be related to #89.  Trying to get the innerHTML of the document works with chromedriver, but fails with phantomjs (version 2.1.1) on the `GET` of `/session/<>/element/<>/property/innerHTML`.

Sensitized to the subtle distinction between `:property` and `:attribute`, I found that this works as an alternative:

```
(execute {:driver driver
          :method :get
          :path [:session (:session @driver)
                 :element element
                 :attribute :innerHTML]})
```

I'm not sure if that's a universal solution, but I did confirm that the same code works against chromedriver.

**Comment by igrishaev** [comment]
@Uunnamed could you please take a look?

**Comment by Uunnamed** [comment]
fixed
