### ISSUE TITLE
Switch window chrome throwing error

### ISSUE THREAD

**Issue by jtackett** [igrishaev/etaoin#190]
Where d is the chrome driver version: 
ChromeDriver 2.45.615355

`(switch-window d (first (get-window-handles d))) `
**returns**
`:message "invalid argument: 'name' must be a string`

`(get-window-handles d)` Works and returns: `["CDwindow-3EFF6B772D5CA841D70A0DBF68AECBEB"]`

**Comment by igrishaev** [comment]
solved in 0.3.1
