### ISSUE TITLE
disconnect-driver resets headless mode

### ISSUE THREAD

**Issue by metametadata** [igrishaev/etaoin#193]
Lib version: 0.3.2.

I've bumped into this issue because I want to start driver process once for the whole test suite and let every test connect/disconnect to it (instead of starting and quiting browser process in every test).

**Steps:**

1) Run headless Chrome driver.
2) Connect to it.
3) Disconnect.
4) Connect again.

**Expected:** nothing happens.

**Actual:** browser window pops up.

Code example:

```clj
(require '[etaoin.api :as e])

(def driver nil)

(alter-var-root #'driver (fn [_]
                           (-> (e/create-driver :chrome)
                               (e/run-driver {:headless true}))))
(alter-var-root #'driver e/connect-driver)
(alter-var-root #'driver e/disconnect-driver)
(alter-var-root #'driver e/connect-driver)
```

It is caused by `disconnect-driver` which erases `:capabilities` from driver atom including `:chromeOptions {:args ["--headless"]}`. Thus second `connect-driver` is made without the needed CLI arg.

Possible solution is to not modify `:capabilities` in `run-driver` and let `connect-driver` generate `:args` depending on `:headless` flag from driver map.

**Comment by Uunnamed** [comment]
Hi, @metametadata 

For your goals, you can use fixtures, like this:
```
(def ^:dynamic *driver*)

(defn fixture-browser [f]
  (let [driver (chrome-headless)]
    (binding [*driver* driver]
      (f))
    (quit driver)))

;; if you want reset some changes (delete cookie, refresh page and etc), or Vice versa,
;; make pre-settings before test you can use fixture like this:
(defn fixture-clear-browser [f]
  (delete-cookies *driver*)
  (go *driver* "https://google.com")
    (f))

;; this is run `once` before running the tests
(use-fixtures
  :once
  fixture-browser)

;;this is run `every` time before each test
(use-fixtures
  :each
  fixture-clear-browser)
```

**Comment by metametadata** [comment]
Thanks. But if I understand everything correctly, I would prefer to not "clear" by hand like this. Connecting/disconnecting looks more bullet-proof (it for sure clears all state, e.g. including local storage) and needs less code.

In either case, the API behaves unexpectedly (IMO of course), the MR doesn't address this root problem.

**Comment by Uunnamed** [comment]
@metametadata 
Could you test this code for yourself?
```
(def ^:dynamic *driver*)

(defn fixture-browser [f]
  (let [driver (chrome-headless)]
    (binding [*driver* driver]
      (disconnect-driver *driver*)
      (f))
    (quit driver)))

(defn fixture-clear-browser [f]
  (connect-driver *driver*)
  (f)
  (disconnect-driver *driver*))

(use-fixtures
  :once
  fixture-browser)

(use-fixtures
  :each
  fixture-clear-browser)
```
in your test use `*driver*` instead `d` of course
for locally it's work, because no need "--no-sandbox" in capabilities
