### ISSUE TITLE
Run selenium IDE fies

### ISSUE THREAD

**Issue by igrishaev** [igrishaev/etaoin#196]
A sample

[aaaa.side.zip](https://github.com/igrishaev/etaoin/files/3107511/aaaa.side.zip)

**Comment by igrishaev** [comment]
https://github.com/SeleniumHQ/selenium-ide/tree/master/tests/examples

**Comment by igrishaev** [comment]
This a huge task needs TBD.

**Comment by igrishaev** [comment]
Задача в следующем: есть такая шутка под названием Selenium IDE. https://www.selenium.dev/selenium-ide/ Это расширение для браузера, которое записывает действия в файл и потом может их проиграть. Кроме этого, из этого файла IDE может нарисовать код на python для тестов и всякие другие штуки.

Это на самом деле прикольно, что можно записать какой-то сценарий, а потом прогнать его. Сценарий может записать специально обученный менеджер или QA, а дальше только автоматизировать прогон.

Хотелось бы, чтобы наша либа могла принять файл, полученный из IDE, и выполнить его. Технически это json со списком дейтвий, у каждого действия одна структура: тип и аргументы. Полагаю, в коде это будет мульт, который по типу действия разруливает, что вызывать.

Проблема в том, что действий достаточно много (см. ссылки выше), и нужно будет реализовать хотя бы основные. Некоторые действия сохраняют результаты в переменные. Это значит, во время прогона понадобится атом локальных переменных. Что-то вроде примитивого интерпретатора. 

Для прогона понадоится файл сценария, базовый урл и некоторые опции, пока непонятно какие. Внутри создается атом локальных переменных. Операции выполняются по очереди. Возможно, одна из опций -- скорость выполнения, т.е. задержка, которую вставлять между командами.

Вторая часть этой же задачи, правда, я пока в ней не уверен -- сгенерить код для тестов. Полагаю, это будет другой мульт, который возвращает замороженный код. Нужно накопить его в список и потом отформатировать каким-то линтером, например `cljfrmt` или другим.

Пока что начать с того, что поставить плагин для брауера. Записать несколько сценариев и посмотреть их содержимое. Потом посмотреть примеры по ссылке: https://github.com/SeleniumHQ/selenium-ide/tree/master/tests/examples

Проверить, что у нас реализовано, а что нет. Для того, что нет, можно пока кидать иключение из мульта или выводить ворнинг. Сюда же писать все вопросы.

**Comment by igrishaev** [comment]
Код пока что лучше держать в отдельном ns, потому что в api у нас уже 3.5К строк.

**Comment by igrishaev** [comment]
Судя по всему, в одном файле могут быть несколько сценариев (они называются suite), и они могут выполняться параллельно. Надо будет сделать опцию, какой тест выполнить (или все, если не задано). Параллельность пока не трогать, пусть один за другим.

**Comment by Uunnamed** [comment]
> Некоторые действия сохраняют результаты в переменные.

если речь идет о https://www.selenium.dev/selenium-ide/docs/en/introduction/control-flow
то я так понимаю используется обычный js браузера для их хранения

да, действий хватает
https://www.selenium.dev/selenium-ide/docs/en/api/commands

думаю для начала попробовать реализовать самые базовые действия, go, click, fill, select, мб alert.

базовый урл также задается в файле, если мы об одном и том же, то его не нужно отдельно передавать.
```
{
  "id": "67d780c1-52b2-412e-901f-2c71cb71aa37",
  "version": "2.0",  // есть версионность
  "name": "kfc",
  "url": "https://anketa.kfc.ru", // базовый урл
  "tests": [{  // массив сценариев, он же suite
    "id": "6871749f-6d63-4c7d-84a2-d8bb000da50a",
    "name": "Untitled",
    "commands": [{
      "id": "69b3973c-5038-46df-9fb3-874776ab3748",
      "comment": "",
      "command": "open",
      "target": "/",
      "targets": [],
      "value": ""
    }, ....
```

алгоритм получается такой
- загружаем файл, преобразуем в edn
- 2 цикла, первый дергает тесты по очереди, второй идет по командам теста
- `"command": "open"` команду преобразуем в кейворд `:open`, и передаем условному мультиметоду `command-run`, остальные аргументы кидая мапкой
- если команда не найдена валимся с эксепшеном.
- если команда завязана на селектор, необходимо пройтись по массиву селекторов используя `query`, остановившись, когда элемент найден, или бросить эксепшн если элемент не найден.
- уведомление о результате выполнения. Есть кстати консольная утила для выполнения https://www.selenium.dev/selenium-ide/docs/en/introduction/command-line-runner

в апи насчитал 96 команд, получается под каждую нужно будет запилить метод, и походу мб допиливать наше апи, если что-то не реализовано

**Comment by igrishaev** [comment]
> Некоторые действия сохраняют результаты в переменные

тут я имел в виду, что некоторые команды (`store` и аналоги) сохраняют значения в переменные, например https://www.selenium.dev/selenium-ide/docs/en/api/commands#store (и ниже). Этим командам можно задать имя переменной, под которыми будут сохранены. Поэтому нужно локальное хранилище, чтобы куда-то их записывать.

Насчет базового урла -- нужна возможность переопределить его в опциях, потому что иногда тест записывается на локальном хосте, а потом надо прогнать на стейджинге. Это просто сделать assoc-in, если урл задан в опциях.

Нужно иметь опцию, чтобы задать имя теста, который хотим выполнить. Это строка, которую мы ищем либо в id, либо name (т.е. айдищник теста или его имя). Если не нашли, кидаем исключение. Если имя не задано, прогоняем все.

Насчет реализации согласен: два цикла, один под тесты, второй под команды, мультиметод. Исключение, если команды нет.

Давай начнем с черновика в отдельном ns, например, ide.clj. Реализуем базовые команды типа click, fill, etc. Добавить в ресурсы простой скрипт, чтобы можно было проверить. Можно начать с Гугла (ввести в поле clojure.org и перейти на официальный сайт). Потом можно сделать локальную страницу для наших нужд.

**Comment by Uunnamed** [comment]
пока разбирался с неймингом, выяснил что 
> `"tests": [{  // массив сценариев, он же suite`

это массив всех тестов из всех suites, а не один suite

```
"suites": [{
    "id": "dd080eea-bd52-44cb-b12e-19ab0ff008d4",
    "name": "Default Suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["fa5c3d93-6f3e-4418-8498-82e1ff30fa64"]
  }, {
    "id": "97c5dfbf-7a3a-4cc2-8b34-2461421b71e4",
    "name": "test2",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["56a0a420-db3e-4dc4-a77e-8a8bf46e35d4"]
  }],
```

т.е. сьюитов может быть несколько, и к каждому может быть привязано несколько тестов.
получается мы можем запустить один или несколько конкретных сьюитов, аналогично тестов, или запустить все подряд.

**Comment by igrishaev** [comment]
Ясно, значит suites это наборы тестов. Мы можем принимать некий парамтер, который может быть как айдишником теста, так и набора.

**Comment by igrishaev** [comment]
Интересен параметр `persistSession`: судя по всему это флаг, нужно ли делить одну сесию для разных тестов. Но это потом уже.

**Comment by igrishaev** [comment]
закрою, потому что остальное уже вкомитили
