### ISSUE TITLE
`click` should only perform clicks when exactly 1 query matches

### ISSUE THREAD

**Issue by vemv** [igrishaev/etaoin#202]
Hi there,

I believe `(click driver {:css ".some-selector"})` should only do its thing if exactly 1 DOM element matches `.some-selector`, not more.

Else tests become ambiguous / nondeterministic.

An exception could be thrown in such cases.

WDYT?

Victor

**Comment by igrishaev** [comment]
Hi Victor! 

The short answer is, no it shouldn't.

The `click` and most of the other functions that accept a query term use low-level find-element API. Whey work in such a way that only the first element gets returned. The changes you propose would break the most part of the API. If you are worried about multiple elements, you could wrap `find-elements*` call and check the number of returned elements.

**Comment by vemv** [comment]
Hi Ivan,

thanks for the answer!

> The changes you propose would break the most part of the API. 

But predictably, there should be other non-breaking (or at least _opt-in_ breaking) strategies to accomplish the same thing, right?

A big use case for Etaoin is testing. It'd be strange if its defaults lead to ambiguous/flaky tests, needing a third-party wrapper.

**Comment by igrishaev** [comment]
Victor,

I believe you may compose your own function which besides clicking on an element also ensures if the query expression returned only a single element.

Here is a draft version which I didn't check:

```clojure
(defn click-single!
  [driver q]
  (let [elements (query-all driver q)]
    (if (> (count elements) 1)
      (throw (new Exception "multiple elements"))
      (click-el driver (first elements)))))
```

Let me know if it works for you and maybe we can push that into the library.
