### ISSUE TITLE
Support Chrome 74 version?

### ISSUE THREAD

**Issue by potapenko** [igrishaev/etaoin#203]
Chrome has been updated to version 74, could you change the version checking from 73 to 74?

**Comment by orestis** [comment]
This error comes from ChromeDriver, not etaoin -- I got it since my Chrome had already downloaded version 74 but still running 73. So when chromedriver 73 tried to launch chrome it got 74 instead, then complained. Updating chromedriver to version 74 fixed things.

**Comment by potapenko** [comment]
Thanx!
