### ISSUE TITLE
Is there a way to get more information when running firefox headless?

### ISSUE THREAD

**Issue by 573** [igrishaev/etaoin#206]
I was trying to run etaoin in a leiningen repl inside a nix-shell session spawned in WSL and what happens is firefox is spawned with the url optionally provided open but then immediately closes.

> user=> (def driver (firefox {:headless true}))
user=> (go driver "https://en.wikipedia.org/")
ExceptionInfo throw+: {:response {:value {:error "invalid session id", :message "Tried to run command without establishing a connection", :stacktrace ""}}, :path "session/589644cd-00c2-44b0-ac39-61ee097c5ba3/url", :payload {:url "https://en.wikipedia.org/"}, :method :post, :type :etaoin/http-error, :port 19425, :host "127.0.0.1", :status 404, :driver {:args ("geckodriver" "--port" 19425), :headless true, :capabilities {:loggingPrefs {:browser "ALL"}, :moz:firefoxOptions {:args ("--headless")}}, :process #object[java.lang.UNIXProcess 0x213dfdff "java.lang.UNIXProcess@213dfdff"], :locator "xpath", :type :firefox, :env nil, :port 19425, :host "127.0.0.1", :url "http://127.0.0.1:19425", :session "589644cd-00c2-44b0-ac39-61ee097c5ba3"}}  slingshot.support/stack-trace (support.clj:201)

Also tested with URL provided:
> user=> (with-firefox-headless nil driver
  #_=> (go driver "https://en.wikipedia.org/"))
>
> SocketTimeoutException Read timed out  java.net.SocketInputStream.socketRead0 (SocketInputStream.java:-2)

**Comment by ivarref** [comment]
Thanks for a nice project! I'd also appreciate this.

**Comment by igrishaev** [comment]
This might be caused by a broken geckodriver version (they have been breaking their stuff).

What to do:
- try to reproduce with the latest version of etaoin/geckodriver
- write a report here.

**Comment by 573** [comment]
With current nix-unstable:
```
nix-shell -p leiningen geckodriver firefox
```
therein:
```
lein update-in :dependencies conj '[etaoin "0.3.6"]' -- repl
```
therein
```
user=> (use 'etaoin.api)
user=> (require '[etaoin.keys :as k])
user=> (def driver (firefox))
```
gives
>Syntax error (ExceptionInfo) compiling at (REPL:1:13).
throw+: {:response {:value {:error "unknown error", :message "invalid argument: can't kill an exited process", :stacktrace ""}}, :path "session", :payload {:desiredCapabilities {:loggingPrefs {:browser "ALL"}}}, :method :post, :type :etaoin/http-error, :port 14358, :host "127.0.0.1", :status 500, :driver {:args ("geckodriver" "--port" 14358), :capabilities {:loggingPrefs {:browser "ALL"}}, :process #object[java.lang.UNIXProcess 0x79a6d487 "java.lang.UNIXProcess@79a6d487"], :locator "xpath", :type :firefox, :env nil, :port 14358, :host "127.0.0.1", :url "http://127.0.0.1:14358"}}

**Comment by igrishaev** [comment]
@Uunnamed could you please try to reproduce? Looks like the message "invalid argument: can't kill an exited process" means that the process was immediatelly stopped with 0 status code, and then we tried to kill it again.

**Comment by Uunnamed** [comment]
Hi @573 
There may be a problem in running the geckodriver from under the root, to check, please try to take a fresh version of etaoin(0.3.8) and run the driver in this way
`(def driver (firefox {:log-stdout "ffout.log" :log-stderr "fferr.log" :args-driver ["--log" "trace"]}))`
and attach the output of the log files here.
I think this is a similar problem
https://github.com/mozilla/geckodriver/issues/1655

**Comment by 573** [comment]
Hi @Uunnamed 
I did as before but with eatoin v0.3.10 and the `def` you suggested .
Direct feedback on the command line is
>user=> (def driver (firefox {:log-stdout "ffout.log" :log-stderr "fferr.log" :args-driver ["--log" "trace"]}))
Syntax error (NoHttpResponseException) compiling at (REPL:1:13).
127.0.0.1:59542 failed to respond

Also got
![Etaoinv0310](https://user-images.githubusercontent.com/123878/93300882-e76ec300-f7f7-11ea-8c63-644332946437.png)

[fferr.log](https://github.com/igrishaev/etaoin/files/5230129/fferr.log)

and

[ffout.log](https://github.com/igrishaev/etaoin/files/5230132/ffout.log)
