### ISSUE TITLE
Connection to remote webdriver

### ISSUE THREAD

**Issue by OStrekalovsky** [igrishaev/etaoin#218]
I can't find information or example how to connect to remote webdriver.
It seems that this library always tries to execute webdriver binary on the local system.
But if i want to make tests in docker (for example with selenoid) it should just send requests to remote machine without calling to local executable.

Could you add an example of such use case in documentation?

**Comment by gmp26** [comment]
We would also find this useful. I'm guessing that what's needed is an interface to a selenium java webdriver https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java

**Comment by igrishaev** [comment]
@OStrekalovsky You're able to connect to a remote driver with ease. Please take a look at the [connect-driver](https://github.com/igrishaev/etaoin/blob/master/src/etaoin/api.clj#L2727) function. I'll update README with an example later.

**Comment by OStrekalovsky** [comment]
> @OStrekalovsky You're able to connect to a remote driver with ease. Please take a look at the [connect-driver](https://github.com/igrishaev/etaoin/blob/master/src/etaoin/api.clj#L2727) function. I'll update README with an example later.

Your example with org.openqa.selenium.remote RemoteWebDriver would be very useful, because the remote driver needs to be properly initializated (i need an capability to specify full URL to remote driver with non empty root path, for example and initializated LocalFileDetector). IMHO, doing this bypassing `boot-driver` function can cause problems and inconsitency in driver configuration.

**Comment by Menthalion** [comment]
@igrishaev To say you can connect with ease is a bit of an overstatement. Have used a lot of selenium (java, python, clj-webdriver), but I haven't found a way in half a day of trying how to use connect-driver to connect to a Selenium hub. That example would help a lot.

**Comment by au-phiware** [comment]
An example would be greatly appreciated.  When I attempt to use `connect-driver` I get the following error:

```
boot.user=> (connect-driver driver {:capabilities {}})

clojure.lang.ExceptionInfo: throw+: {:response "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n 
 <meta charset=\"UTF-8\">\n  <link rel=\"stylesheet\" type=\"text/css\" href=\"/assets/display
helpservlet.css\" media=\"all\"/>\n  <link href=\"/assets/favicon.ico\" rel=\"icon\" type=\"im
age/x-icon\" />\n  <script src=\"/assets/jquery-3.1.1.min.js\" type=\"text/javascript\"></scri
pt>\n  <script src=\"/assets/displayhelpservlet.js\" type=\"text/javascript\"></script>\n  <sc
ript type=\"text/javascript\">\n    var json = Object.freeze('{\"consoleLink\": \"\\u002fwd\\u
002fhub\",\"type\": \"Grid Node\",\"class\": \"org.openqa.grid.web.servlet.DisplayHelpHandler$
DisplayHelpServletConfig\",\"version\": \"3.141.59\"}');\n  </script>\n</head>\n<body>\n\n<div
 id=\"content\">\n  <div id=\"help-heading\">\n    <h1><span id=\"logo\"></span></h1>\n    <h2
>Selenium <span class=\"se-type\"></span>&nbsp;v.<span class=\"se-version\"></span></h2>\n  </
div>\n\n  <div id=\"content-body\">\n    <p>\n      Whoops! The URL specified routes to this h
elp page.\n    </p>\n    <p>\n      For more information about Selenium <span class=\"se-type\
"></span> please see the\n      <a class=\"se-docs\">docs</a> and/or visit the <a class=\"se-w
iki\">wiki</a>.\n      <span id=\"console-item\">\n        Or perhaps you are looking for the 
Selenium <span class=\"se-type\"></span> <a class=\"se-console\">console</a>.\n      </span>\n
    </p>\n    <p>\n      Happy Testing!\n    </p>\n  </div>\n\n  <div>\n    <footer id=\"help-
footer\">\n      Selenium is made possible through the efforts of our open source community, c
ontributions from\n      these <a href=\"https://github.com/SeleniumHQ/selenium/blob/master/AU
THORS\">people</a>, and our\n      <a href=\"http://www.seleniumhq.org/sponsors/\">sponsors</a
>.\n   </footer>\n  </div>\n </div>\n\n</body>\n</html>", :path "session", :payload {:desiredC
apabilities {}}, :method :post, :type :etaoin/http-error, :port 5555, :host "172.18.0.5", :sta
tus 404, :driver {:type :chrome, :host "172.18.0.5", :port 5555, :url "http://172.18.0.5:5555"
, :locator "xpath", :capabilities {}}}
```

**Comment by Uunnamed** [comment]
> I can't find information or example how to connect to remote webdriver.
> It seems that this library always tries to execute webdriver binary on the local system.
> But if i want to make tests in docker (for example with selenoid) it should just send requests to remote machine without calling to local executable.
> 
> Could you add an example of such use case in documentation?

Example:

```
(connect-driver driver {:capabilities {:chromeOptions {:args ["--no-sandbox"]}}})

```

**Comment by igrishaev** [comment]
Thanks Alex, it would be nice to add this into Readme.

**Comment by igrishaev** [comment]
@OStrekalovsky now there is an example in readme file, you're welcome to check it out.
