### ISSUE TITLE
Get selected option

### ISSUE THREAD

**Issue by kiramclean** [igrishaev/etaoin#220]
Is there currently a way to get a hold of the currently selected option in a `select`? It looks like the Java implementation exposes `.getFirstSelectedOption()` (used e.g. [like this]( https://stackoverflow.com/questions/11934966/how-to-get-selected-option-using-selenium-webdriver-with-java)). I was wondering if there's anything similar available in this library. I want to test that the correct default is selected in a dropdown.

**Comment by kiramclean** [comment]
I ended up using `get-element-value` on the `select` element.. it gives me the value, obviously, not the text the user actually sees, but is close enough.

**Comment by Uunnamed** [comment]
Hi @kiramclean 
Try to use two commands together `get-element-value`, `get-element-text` and CSS or Xpath selectors.
For example:
```
(get-element-value driver {:tag :select})
;; => "search-alias=baby"
(get-element-text driver {:css "[value=\"search-alias=baby\"]"})
;; => "Baby"
etaoin.api> 
```
