### ISSUE TITLE
Connection refused: connect

### ISSUE THREAD

**Issue by jtackett** [igrishaev/etaoin#221]
I am seeing `Connection refused: connect` often and with no pattern. I have not been able to resolve this issue or find a pattern. Is this an issue we are aware of?

Chrome: 78
etaoin: 0.3.1

**Comment by igrishaev** [comment]
I maybe a bug a webdriver that you've been using these days. We'll try to reproduce.

**Comment by igrishaev** [comment]
After some attempts we didn't manage to reproduce. Probably it was a buggy version of the driver. Closing.
