### ISSUE TITLE
Impossible to download files with firefox / firefox-headless

### ISSUE THREAD

**Issue by zilti** [igrishaev/etaoin#222]
As the title says, downloading files seems to not be possible with etaoin and Firefox. I always get the modal dialog window asking me if I want to open or save the file. I followed the instructions in the Readme.

**Comment by anthonygalea** [comment]
Hi @zilti have you tried [setting the download directory](https://github.com/igrishaev/etaoin#file-download-directory)?

**Comment by zilti** [comment]
Yes, I did set the download directory

**Comment by anthonygalea** [comment]
On firefox+macos I didn't get the modal. What OS are you on?

**Comment by zilti** [comment]
I'm on Linux, this issue is on both Arch Linux and OpenSUSE Tumbleweed.

**Comment by rj3d** [comment]
I don't know if you've figured it out, but you also have to tell Etaoin/Firefox to not show the download window. Below is the code that I use to download files. You might need to add filetypes to the list if yours isn't there.

```clojure
(etaoin/firefox {:headless true
                  :size [2048 1360]
                  :prefs {:browser.download.dir
                          "/tmp/downloads/"
                          :browser.helperApps.neverAsk.saveToDisk
                          "application/xml,text/plain,text/xml,text/csv,image/jpeg,application/octet-stream,application/excel,application/vnd.ms-excel,application/vnd.msexcel"
                          :browser.download.folderList
                          2
                          :browser.download.manager.showWhenStarting
                          false
                          :pdfjs.disabled
                          true}})
```

**Comment by zilti** [comment]
Yes, that solves it indeed! 👍 Thank you very much!
