### ISSUE TITLE
Clj-http version bump

### ISSUE THREAD

**Issue by bhougland18** [igrishaev/etaoin#227]
I forked this project to see if bumping the version of Clj-http would cause any major issues.  If I got this working would you accept a PR?  I just want to understand if you are using version 2 of this library for a particular reason.

**Comment by zilti** [comment]
Well, version 3.10.1 does not work, I can tell you that much. Because I tried using that alongside Etaoin, and it errors out.

**Comment by igrishaev** [comment]
- Bump the `clj-http` lib to the latest version;
- Update the code so that there is no issues with that.
