### ISSUE TITLE
extend xpath statements

### ISSUE THREAD

**Issue by igrishaev** [igrishaev/etaoin#23]
try to improve xpath clauses to support `text() = ...`, `contains` and some related features.

**Comment by jaaqo** [comment]
Would it be as simple as extending here:

https://github.com/igrishaev/etaoin/blob/master/src/etaoin/api.clj#L442
```clojure
pair (fn [[key val]]
        (format "[@%s='%s']"
          (name key)
          (get-val val)))
```
to branch on key? Like:
```clojure
pair (fn [[key val]]
        (case key
         :text (format "[.//text()='%s']"
                (get-val val))
         :contains (format "[contains(., '%s'])"
                    (get-val val))
         (format "[@%s='%s']"
           (name key)
           (get-val val)))
```

**Comment by igrishaev** [comment]
Well, I've been thinking on extending xpath expressions to support functions. I believe, they could be prepended with `:fn/` namespace, say `:fn/text "example"` that is turned into `text() = "example"`.

Before we start fixing the code, could you provide some Xpath examples please?

**Comment by igrishaev** [comment]
The problem here is to prevent mixing HTML attributes with functions.

**Comment by jaaqo** [comment]
I see your point. Here's simple function examples for `text`, `contains` and `normalized-space`.

1. Select a button with text content 'Click me!'
`button[text() = 'Click me!']`
=>
`<button>Click me!</button>`

- Note that text tests against text nodes so
`<button>Click <b>me!</b></button>`
should fail

2. Select an input field whose class contains 'user'
`input[contains(@class, 'user')]`
=>
`<input type="text" class="390user949abc" />`

3. Select a paragraph tag which contains text 'Skadoodle'
`p[contains(text(), 'Skadoodle')]`
=>
`<p>Lorem ipsum dolor Skadoodle sit amet</p>`

4. Select button with text '   Click      me!   ', space normalized
`button[normalize-space() = 'Click me!']`
=>
`<button>   Click      me!   </button>`

**Comment by jaaqo** [comment]
Call syntax should probably be recursive in nature allowing to specify arguments as (_context_, _string_) enabling to use child selectors as the context. Like in example 3.

`{:fn/contains [_context_, _string_]}`
or
`{:fn/contains _string_}` defaults to current node context?

**Comment by igrishaev** [comment]
Well, since text() and contains() appear frequently, we may have special processing for them.

Say, for `div[text() = 'test']` we could implement `{:tag :div :fn/text "test"}` syntax.
For `contains` and other functions with multiple arguments, I cannot guess a proper syntax at the moment.

**Comment by igrishaev** [comment]
In general, it reminds me the ORM problem when we are trying to map plain text on data structures.

**Comment by igrishaev** [comment]
solved
