### ISSUE TITLE
selenium in docker, can not create session

### ISSUE THREAD

**Issue by erdos** [igrishaev/etaoin#24]
Hi, 

I would like to use `etaoin 0.1.6` with a selenium in docker:
`docker run -p 4444:4444 selenium/standalone-firefox:3.4.0-chromium`

I am trying to connect the following way:

```clojure
(require '[etaoin.api :exclude [wait] :refer :all])
(def driver (connect-driver (create-driver :firefox {:port 4444})))
````
Here an exception is thrown since the `create-session` function calls to `http://localhost:4444/sessions` (page does not exist). I think the correct url would be `http://localhost:4444/wd/hub/session`.

**Comment by igrishaev** [comment]
Etaoin is not designed to work together with Selenium. `wd/hub/session` path is a part of JsonWire protocol that is used in Selenium. `sessions` path is a part of Webdriver protocol. Etaoin uses the second one. All you need is to install a driver locally (firefox or chrom) and then perform something like that:

```
(with-firefox {...} driver
   (your code here))
```

I may guess you even don't need running Docker image for that.

**Comment by erdos** [comment]
I understand it now, thank you!

**Comment by igrishaev** [comment]
Great, closing. Please come back once you need help.
