### ISSUE TITLE
Add headless-chrome support

### ISSUE THREAD

**Issue by igrishaev** [igrishaev/etaoin#25]
https://developers.google.com/web/updates/2017/04/headless-chrome

**Comment by igrishaev** [comment]
```
(def cap
  {:chromeOptions
   {:binary "/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary"
    :args ["--headless"]}})

(defn fixture-driver [f]
  (with-chrome {:desired-capabilities cap} driver
    (binding [*driver* driver]
      (f))))
```

**Comment by agzam** [comment]
What about headless instance of Chrome running in a docker container. This is a must for tests that need to run on CI.

**Comment by igrishaev** [comment]
@agzam I've been experimenting with that recently. In docker, Chrome behaves quite strange. For example, it cannot click on some elements.

**Comment by igrishaev** [comment]
@agzam if you are talking about CircleCI, they have preinstalled chrome and chromedriver with $DISPLAY env variable properly set. We use etaoin on Circle as well without docker.

**Comment by igrishaev** [comment]
done. see `(headless)` and `(with-headless)`

**Comment by cjsauer** [comment]
>with $DISPLAY env variable properly set.
@igrishaev do you have a quick example of this? I'm struggling hard to get etaoin running on CircleCI right now...any help would be appreciated.

**Comment by cjsauer** [comment]
To be a bit more specific, I keep getting this error on CircleCI even though my tests pass locally:

```
Testing in chrome browser
Uncaught exception, not in assertion.
expected: nil
  actual: clojure.lang.ExceptionInfo: throw+: {:type :etaoin/timeout, :message nil, :timeout 20, :interval 0.33, :times 61, :predicate #object[etaoin.api$wait_exists$fn__5152 0x33eab2e8 "etaoin.api$wait_exists$fn__5152@33eab2e8"]}
```

**Comment by cjsauer** [comment]
It very well may be related to the fact that I'm attempting access my app using the `file://` protocol. My project is front-end only, so I don't have a server to launch and access. The logs show that the CircleCI chromedriver is trying to navigate to this file:

```
Visiting file:///root/my-project/resources/public/index.html
```

**Comment by igrishaev** [comment]
@cjsauer yes, that might be an issue when you open your app as a local HTML file. In addition to a screenshot, you may dump current HTML markup into a file and examine it.

**Comment by igrishaev** [comment]
@cjsauer for docker setup, there is an issue #47 with snippets grabbed from slack channel.
