### ISSUE TITLE
shrotcut or macros for connect-create driver

### ISSUE THREAD

**Issue by Uunnamed** [igrishaev/etaoin#280]
Если требуется только коннект к уже запущенному драйверу приходится постоянно писать конструкцию типа:
(def driver (connect-driver (create-driver :chrome (:chrome default-opt))))

**Comment by Uunnamed** [comment]
возможно сделать это через флаг, если есть пропускаем шаг запуска драйвера при старте, и уничтожение процесса при выходе

**Comment by igrishaev** [comment]
Ivan Grishaev, [12 Aug 2020, 10:51:32]:
мне кажется, надо упростить функции create-, connect-, run-, boot и тд. Сейчас их зоопарк.

У нас по сути два варианта -- поднять локальный драйвер и подключитсья к нему, либо подключиться к удаленной машине.

может, оставить две функции: run-driver и connect-driver, то  есть запустить локальный или подключиться к удаленному

**Comment by Uunnamed** [comment]
Как оказалось из-за особенности запуска джавой процессов, при попытке запуска процесса на порту который занят, происходит форк уже существующего процесса. Другими словами присоединиться к уже запущенному драйверу можно просто передав его порт, при создании драйвера `(def driver (chrome {:port 9515})`.
Нужно поправить доку, чтобы отразить эту возможность
