### ISSUE TITLE
Refactor run/connect commands

### ISSUE THREAD

**Issue by igrishaev** [igrishaev/etaoin#295]
TBD

**Comment by igrishaev** [comment]
В этой задаче я хочу разобраться с зоопарком функций, которые служат для создания драйвера, запуска процесса, подключения к нему и обратных действий. Мне кажется, их слишком много, что вносит путаницу. Вдобавок мы используем атом и изменяем его.

Код должен отвечать на запросы пользователей. Когда кто-то хочет рулить браузером, у него по сути два варианта: запусттиь браузер локально или подключиться к удаленной машине. Сейчас у нас хорошо работает только первы вариант -- запуск и подключение локально. С подключаением к удаленной машине нужно приседать: вручную создавать драйвер, потом подключаться к нему.

Рассмотрим каждый сценарий. Локальный сценарий можно разбить на два этапа. Это старт процесса драйвера и подключение к локальному хосту. Удаленный сецнарий -- просто подключение. В идеале хотелось бы видеть функции (chrome) и (chrome-connect), где первая запускает локальный хром, а вторая подключается к удаленной машине. Дополнительно предлагаем макросы (with-chrome) и (with-chrome-connect), чтобы закрывать ресцрсы автоматом.

Есть и другое предложение: пусть функция (chrome) и аналоги угадывает, что от нее хотят. Например, если мы не указали хост, считаем, что это локальный сценарий. В этом случае запускаем драйвер на машине пользователя и подключаемся. Если хост указан, это удаленный случай, и мы только подключаемся.

**Comment by igrishaev** [comment]
Нужно сделать так, чтобы на каждый сценарий у пользователя была простая функция или макрос. Например, чел зарегался в облачном сервисе для тестирования сайтов. Ему выдали хост и порт для хрома, который крутится на условной windows 7 в облаке. Челу нужно подлючиться к этому хрому, зайти на свой сайт и что-то потыкать. Как будет выглядеть его код? 

```clojure
(def host "client523624.some.cloud.platform.com")

(def port 66946)

(deftest test-my-site-in-windows7
  (with-chrome-connect [driver {:host host
                                :port port}]
    (doto driver
      (go "http://mysite.com")
      (click {:this :button})
      (click {:that :link}))))
```

**Comment by igrishaev** [comment]
Может быть, пока что создать функции `chrome-connect` и `with-chrome-connect`, которые не запускают процесс, а только подключаются? Тогда не придется переделывать текущий код. А функции `driver-create`, `driver-connect`, `driver-run`, `boot-driver` мы сделаем служебными: объявим приватными и поставим спереди минус (`-boot-driver`), чтобы не было соблазна их использовать.

**Comment by igrishaev** [comment]
В целом у задачи два пункта:
- четко обозначить локальный и удаленный сценарии. Описать второй случай в readme.
- решить, что мы высталяем пользователю как конечное API, а что для внутренних нужд.

**Comment by igrishaev** [comment]
Что сделать по по этим пунктам:

- проверить, как бы сейчас выглядел код для подключения к удаленной машине. Представить, что нам дали креды для уделенной машины, и нужно написать тесты. Адаптировать библиотеку так, чтобы кода было как можно меньше.

- обозначить, какие функции и методы станут приватными. Убедиться, что мы не упоминаем их в readme. Сделать их приватными и поставить спереди минус.

**Comment by igrishaev** [comment]
- добавить в readme пример с удаленным подключением.

**Comment by Uunnamed** [comment]
> В целом у задачи два пункта:
> 
>     * четко обозначить локальный и удаленный сценарии. Описать второй случай в readme.

Есть еще момент, что нужно подключится к локально запущенному драйверу, к тому же докеру. На данный момент, у нас это отрабатывает, через хак самой джавы которая форкает процесс, но не факт что мы именно к нему коннектимся в итоге, и это все же не явно получается.
т.е. имхо угадывать не получится, нужно или явно указать через флаг типо `:connect-only` в опциях и разруливать этот флаг в `boot`. либо действительно делать функции с префиксом `-connect` но тогда объем кода увеличится.


>     * решить, какие API мы выставляем пользователю, а что остается для внутренних нужд.

тут согласен, народ эти функции использует отдельно, в основном как раз из-за того, что нужно делать коннект.
поэтому если закрыть вопрос, то можно сделать их приватными.

**Comment by igrishaev** [comment]
Да, случай с докером тоже в тему. И еще хотел добавить, что вариант с форком не как-то не очень. Это происходит неявно и поэтому трудно расследовать. Кроме того, форк процессов не предусмотрен в винде, поэтому как поведет себя драйвер там, непонятно.

Мне кажется, мы должны вручную проверять доступность дравйвера. Проще всего это сделать, постучавшись в указанный порт. Если он занят, то мы кидаем исключение с текстом, что нельзя поднять драйвер на этом порту. Это при условии, что порт задан явно. А если порт пустой, мы выбираем случайный порт.

**Comment by igrishaev** [comment]
Да, вариант с угадайкой отметается, потому что под `localhost:1234` может иметься в виду драйвер в докере. Кстати, вспомнил -- одно время хотел добавить в readme примеры с запуском в докере, но руки не дошли.

У флага `:connect-only` недостаток в том, что его надо помнить, и в целом он как-то неочевиден. Запуск и коннект это разные действия, поэтому лучше разделить их на отдельные функции. Да, кода получится больше, зато так будет понятнее.

Еще я понял, что до сих пор использовал неверный термин. В селениуме запущенный драйвер называется удаленным (remove), и нам лучше использовать такой же термин. Т.е. у нас будут функции chrome, firefox и макросы with-chrome, with-firefox, которые запускают локальный драйвер. Мы добавим к ним -remote варианты: chrome-remote, firefox-remote и макросы with-chrome-remote. Так будет работать даже для драйвера в докере. Остальные функции спрячес для себя. Нормально?

**Comment by igrishaev** [comment]
Соберу еще раз пункты:

- remote-версии функций и макросов
- спрятать остальные функции, убрать их из readme
- обновить readme с примерами remote
- добавить примеры с докером

**Comment by igrishaev** [comment]
- не позволять форк процесса в локальном запуске. Если порт указан, но занят, то исключение. Если не указан, но брать случайный. Лучше даже убрать дефолтные порты, чтобы снизить риск конфликта.

**Comment by igrishaev** [comment]
На форк можно даже добавить тесты. Запускаем из джавы драйвер на стандартном порту. Потом стартуем (chrome) с таким же портом -- должны получить исключение.

**Comment by igrishaev** [comment]
Мне кажется, случай с форком выходит за рамки задачи, поэтому я вынесу в отдельную.

**Comment by Uunnamed** [comment]
по самим функциям у нас их 4 получается
`boot-driver`, `create-driver`, `run-driver`, `connect-driver`
`boot-driver` мы оставляем как есть и делаем `remote-boot-driver` внутри `create-driver` + `connect-driver` и на него вяжем все remote функи, так?

**Comment by igrishaev** [comment]
В целом да. Основная задача -- разделить эту кашу на публичное и приватное API, и тогда сразу станет легче.

 boot-driver, create-driver, run-driver, connect-driver, а так же disconnect-driver, stop-driver -- это приватные функции. Их реализация пусть не меняется, но они должны стать приватными и с дефисом перед ними. Кроме того, нужно перенести их докстринги в публичные варианты (но это можно сделать отдельно).

публичные функции это все именные (chrome, firefox, with-chrome, etc), их макросы, a так же with-driver. К ним добавятся -remote-варианты. Уточню, что -remote лучше ставить на конец имени. Реализовать их можно так же через условный -boot-driver-remote через partial, чтобы было общая точка входа.

**Comment by igrishaev** [comment]
Думаю, можно двигаться итеративно, чтобы не наломать дров. Например, сперва добавить -remote функции. Потом отрефакторить приватные, потом причесать readme. Можно даже отдельными pr, потому что задача жирная. Если тесты будут проходить после каждого PR, то норм.

**Comment by igrishaev** [comment]
только еще момент: boot-driver можно оставить публичной функцией, потому что точка входа для именных функций. Гипотетически ее можно использовать в тестах в цикле, чтобы запускать драйвер по кейворду.

**Comment by igrishaev** [comment]
Вчера мы вкомитили -remote функции, и сегодня я что-то засомневался. Может, будет лучше одно из двух:

- передать флаг `{:remote true}` в обычный драйвер. В этом случае мы пропускаем шаг запуска процесса
- сыграть в угадайку: если хост не задан, это локальный драйвер, и мы запускаем процесс (порт при этом можно указать). Если хост задан (в т.ч. localhost), считаем, что это remote и подключаемся.

Основной вопрос в том, как будет удобнее пользователю. Сейчас мы предлагаем -remote-варианты обычных функций. Может, с флагом будет проще?

**Comment by Uunnamed** [comment]
да, я примерно об этом и говорил
с точки зрения пользователя , мне проще выбрать из вариантов табом `-remote` чем писать `{:remote true}` единственный момент, это нужно как то явно показать, что для ремота нужно указать порт, либо брать его из дефолтов

**Comment by igrishaev** [comment]
Дублирую пункты:

- [ ] сделать запуск процесса в зависимости от хоста
- [ ] спрятать служебные (не именные) функции (кроме boot-driver и quit), убрать их из readme
- [ ] обновить readme с примерами remote
- [ ] добавить примеры с докером
