### ISSUE TITLE
Update API Docs

### ISSUE THREAD

**Issue by AdamFrey** [igrishaev/etaoin#32]
The API docs that are hosted at http://grishaev.me are out of date. Notably they don't have entries for any of the wait functions like `wait-visible`, etc.

**Comment by igrishaev** [comment]
For now, I pushed a new version of docs, but some functions still don't have docstrings in the code  and thus not preset in HTML.

I will be able to write docstrings in two weeks maybe since I'm traveling abroad at the moment. Or maybe you may help me with them.

**Comment by igrishaev** [comment]
I added docstrings to some functions, please check http://grishaev.me/etaoin/etaoin.api-api.html#etaoin.api/wait-exists for example.

Closing.
