### ISSUE TITLE
How to make Chrome DevTools Protocol calls?

### ISSUE THREAD

**Issue by joncol** [igrishaev/etaoin#324]
How do I make a call to a CDP method?

I basically want to call `Network.getResponseBody` for a specific request ID, so that I can inspect the actual body of the response to a call that was made "behind the scenes" when visiting a certain page.

I didn't find any clear explanation if and how that can be done in the documentation.

Link to CDP method: https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-getResponseBody

**Comment by igrishaev** [comment]
Hi @joncol!

Chrome DevTools Protocol has its own protocol and our library doesn't cover it. You may look closer to the documentation. It says, there are several HTTP endpoints available on port 9222 when you run chrome with the flag ` --remote-debugging-port=9222`

https://chromedevtools.github.io/devtools-protocol/#endpoints

Also, there is the Websocket endpoint `/devtools/page/{targetId}` which is maybe you're looking for.

Anyway, as I said, the Chrome DevTools Protocol is a separate thing with its own protocol, so the library gives nothing to work with it.

**Comment by joncol** [comment]
Thanks! I'll look at those links you supplied... Have a good one!
