### ISSUE TITLE
Timeout while waiting to connect to the driver

### ISSUE THREAD

**Issue by Macroz** [igrishaev/etaoin#338]
Hi,

Thanks for etaoin! 

We run our browser tests in our CI environment and we have a randomly failing browser test because booting the driver times out. I was looking at the code and noticed that `wait-running` uses the default parameters to `wait-predicate` i.e. 20 second delay. I was wondering if this could be parametrized so I could specify a longer time? Would you accept a PR for this tiny enhancement? 

It is possible that it would not solve our problem and in fact the driver has failed to start for other reasons. Any ideas for debugging that would be helpful too. So far we never got this problem while running on development machines.

We are currently running 0.3.6, but I see this part at least hasn't changed.

Here's the original exception trace:
```
Exception: clojure.lang.ExceptionInfo: throw+: {:type :etaoin/timeout, :message nil, :timeout 20, :interval 0.33, :times 61, :predicate #object[etaoin.api$wait_running$fn__64780 0x28fa298a "etaoin.api$wait_running$fn__64780@28fa298a"]}
{:type :etaoin/timeout, :message nil, :timeout 20, :interval 0.33, :times 61, :predicate #object[etaoin.api$wait_running$fn__64780 0x28fa298a "etaoin.api$wait_running$fn__64780@28fa298a"]}
 at slingshot.support$stack_trace.invoke (support.clj:201)
    etaoin.api$wait_predicate.invokeStatic (api.clj:1891)
    etaoin.api$wait_predicate.invoke (api.clj:1870)
    etaoin.api$wait_running.invokeStatic (api.clj:2025)
    etaoin.api$wait_running.doInvoke (api.clj:2022)
    ...
    etaoin.api$connect_driver.invokeStatic (api.clj:2779)
    etaoin.api$connect_driver.doInvoke (api.clj:2762)
    ...
    etaoin.api$boot_driver.invokeStatic (api.clj:2831)
    etaoin.api$boot_driver.invoke (api.clj:2815)
```

**Comment by Uunnamed** [comment]
Hi @Macroz

Hi @Macroz!

Since 0.3.9, we decreased the default timeout from 20 to 7 seconds. To compensate that, we also added a `wrap-default-timeout` which sets the default timeout globally for the body. You can also pass the timeout into the all (wait-<something>) functions as follows:

```
(wait-visible ... {:timeout 30})
```

Most likely, changing the timeout won't solve the problem. Please try to use the latest version of etaoin (which is 0.3.10 now). Add the `wrap-default-timeout` macro and let us know how does it go. You're also welcome to submit the code you use to bootstrap your tests.

**Comment by Macroz** [comment]
Here is the line where that `boot-driver` call is made.

https://github.com/CSCfi/rems/blob/master/test/clj/rems/browser_test_util.clj#L92

I can try with the `wrap-default-timeout` with a longer value to see if the problem disappears for us.

**Comment by igrishaev** [comment]
Hey @Macroz! Looks like the issue with your tests has been solved, hasn't it? https://github.com/CSCfi/rems/pull/2389

**Comment by Macroz** [comment]
Yes, many thanks for the answers and the progomaö feature. I will try this in our CI pipeline. I will also close this issue because there is nothing acute. I will get back to you if I discover anything else. 

It's possible that the browser actually fails to start sometimes, but then I will look at how to make it retry a few times. So far retrying manually in the CI pipeline eventually works.
