### ISSUE TITLE
Cannot initialize driver

### ISSUE THREAD

**Issue by ds2643** [igrishaev/etaoin#34]
Attempting to follow along with the instructions provided in the [README](https://github.com/igrishaev/etaoin), I ran into an error initializing a driver instance:
```
sample.core> (use 'etaoin.api)
nil
sample.core> (require '[etaoin.keys :as k])
nil
sample.core> (def driver (firefox))
                    java.io.IOException: error=2, No such file or directory
                    java.io.IOException: Cannot run program "geckodriver": error=2, No such file or directory
clojure.lang.Compiler$CompilerException: java.io.IOException: Cannot run program "geckodriver": error=2, No such file or directory, compiling:(form-init2904624762632379775.clj:47:21)
```
I expect that I'm walking a well-traveled road over here. Please point out what I'm doing wrong if its something obvious.

**Comment by ds2643** [comment]
Sorry I jumped the gun: Looks like I failed to finish reading the instructions and installing the driver.

**Comment by igrishaev** [comment]
@ds2643 Hi David!

Yes, you need to install the drivers first.
