### ISSUE TITLE
get-url does not return the newly opened tab's URL

### ISSUE THREAD

**Issue by stardiviner** [igrishaev/etaoin#352]
Hi, sorry to ask a newbie question again. I asked in Slack channel, but no response, so I asked here again.

Here is the background this commit #350 , I can't use `(browser/get-url driver)`. I tried many times with fresh new chrome instance. Still get the old URL. Is there some tricky here?

**Comment by Uunnamed** [comment]
Hi, @stardiviner 

In your case, clicking on the link opens a new window, and you need to switch to it to start interacting with its content
example from our tests:
```
(deftest test-switch-window
  (let [init-handle   (get-window-handle *driver*)
        init-url      (get-url *driver*)
        _             (click *driver* :switch-window)
        new-handles   (get-window-handles *driver*)
        new-handle    (first (filter #(not= % init-handle) new-handles))
        _             (switch-window *driver* new-handle)
        target-handle (get-window-handle *driver*)
        target-url    (get-url *driver*)]
    (is (not= init-handle target-handle))
    (is (= 2 (count new-handles)))
    (is (= new-handle target-handle))
    (is (not= init-url target-url))))
```

**Comment by stardiviner** [comment]
Hi, @Uunnamed , 😸   nice to meet you again, thanks for your answer.

Interesting, is this window means a browser tab? This means I have to manually switch window, right.
Problem solved with following code:
```clojure
....
(browser/switch-window driver (second (browser/get-window-handles driver)))
(browser/get-url driver)
```
I found the function `get-window-handles` returns vector like this:
```
["CDwindow-5BD78E0CD890B09FDEC2563856BC863B" "CDwindow-44E8C2F4F2C039C32E939193DC3FEE5A"]
```
Is there other more human-readable way to switch window other than upper let-binding?

**Comment by Uunnamed** [comment]
Hi, @stardivine, likewise =)
Yep,  "window" in this context means a browser tab. 
I added the `switch-window-next` function to switch between "windows", it will be available after the next release. Thank you for your feedback!

**Comment by stardiviner** [comment]
That's really helpful function. Sweet! Thanks
