### ISSUE TITLE
ClassNotFoundException when (use 'etaoin.api)

### ISSUE THREAD

**Issue by Outrovurt** [igrishaev/etaoin#369]
I'm falling over at the very first hurdle, when I type:

```clojure 
(use 'etaoin.api)
```

I immediately get the following error
```
Syntax error (ClassNotFoundException) compiling at (clj_http/conn_mgr.clj:1:1).
org.apache.http.conn.ssl.DefaultHostnameVerifier

```

Bizarrelly enough the following works:

```clojure
(require 'etaoin.keys)
```

I have installed both chromedriver (it came with Chromium) and geckodriver (which I installed on my ArchLinux system.)

Does anyone have any idea how to get past this? Thanks.

**Comment by igrishaev** [comment]
The `(require 'etaoin.keys)` line works because the `keys` modules don't depend on clj-http. There is something wrong with clj-http in your case. It looks like your project specifies some old version of clj-http or org.apache.httpcomponents libraries.

Try to declare the deps explicitly, for example:

```
[clj-http "3.10.1"]
[org.apache.httpcomponents/httpclient "4.4.1"]
```

**Comment by Outrovurt** [comment]
Ah great, that fixed it, thanks a lot.

I've been playing around with this all morning and I have to say, what a brilliant library you've created. It's really easy to use and seems to cover everything I need and a lot more I didn't know I needed.

I've been putting off writing front-end tests for a long time because every time I've gone to find out how to do this in Selenium, I've been overwhelmed by everything you need to download and configure before you can start doing any testing. This on the other hand was incredibly straightforward and has been a pleasure to use. Thank you very much for all your work.
