### ISSUE TITLE
Cljs-repl

### ISSUE THREAD

**Issue by agzam** [igrishaev/etaoin#37]
How can I piggieback onto a driver instance and get a Cljs REPL connected to it?

**Comment by agzam** [comment]
Well, I guess it's not different than any other way - for some reason I thought it would be easier. Browser still has not only to navigate to something like `http;//localhost:8090`, but also has to run piece of compiled clojurescript that has `(repl/connect "http://localhost:8090/repl")`.

**Comment by igrishaev** [comment]
@agzam I'm not sure that issue relates to the library itself. I believe, you may connect to the browser using figwheel.

Closing.

**Comment by agzam** [comment]
No it's not related to the library, but I think it would be nice to have this documented, or some kind of example added to the project, because currently with Clojurescript it is fairly easy to get into nodejs REPL (you can even import js libs straight out of `node_modules` dir - which is truly awesome). However, running and connecting to a full-featured browser REPL (not emulated, not Rhino but a real browser) requires a bit of plumbing.
This lib I believe can simplify things greatly and reduce all manual steps required (with the exception of typing the initial command). I may give it a shot when I have free time.

**Comment by igrishaev** [comment]
Well, you manage to implement that, please post the code here, I'll add it as a use case in readme.
