### ISSUE TITLE
Query element with system id returned from query-all

### ISSUE THREAD

**Issue by sunng87** [igrishaev/etaoin#375]
It seems missing in api or docs for data returned from `query-all`. In my usecase, I'm going to fetch an attribute of all matched elements. I'm using css selector with `query-all` for the element. However, there is no chance to convert these system ids into element that can be used with `get-element-attr`.

A `el` function is welcomed to convert a system id to an element

**Comment by Uunnamed** [comment]
Hi, @sunng87
`query-all` returns an array of elements(el). To use this `el` with functions such as `get-element-attr`, there are separate functions ending in `-el` - `get-element-attr-el`. Functions without ending `-el` do not use `el` directly, but the `query` parameter and function are used to search for it. Thus, for functions returning `el`-s, you can simply use the ending on `-el` without any convertions.

**Comment by sunng87** [comment]
Thank you for clarification!
