### ISSUE TITLE
Capabilities are overwritten by merge

### ISSUE THREAD

**Issue by AdamFrey** [igrishaev/etaoin#39]
I was surprised by the behavior of the way etaoin merges default and user-passed capabilities.

I tried running 
```
(e/headless {:desired-capabilities
                      {:chromeOptions
                       {:args ["--proxy-server=localhost:12345"]}}}
```

and to my surprise a non-headless chrome window opened up.

Looking at the Etaoin source I found the answer. In the default options table, etaoin has these options for `:headless`

```
(def defaults
  {...
   :headless {:port 9515
                     :path "chromedriver"
                     :capabilities {:chromeOptions {:args ["--headless"]}}}})
```

But then in `connect-driver` user supplied options are merged with default options:

```
(deep-merge cap-default cap) 
```

and the implementation of `deep-merge` just takes the last value it sees for a nested key:

```
(defn deep-merge
  [& vals]
  (if (every? map? vals)
    (apply merge-with deep-merge vals)
    (last vals)))
```
Does it make sense to change the implementation of deep-merge to concatenate sequential values? Like:
```
(deep-merge {:chromeOptions {:args ["arg1"]}} {:chromeOptions {:args ["arg2"]}}) => {:chromeOptions {:args ["arg1" "arg2"]}}
```

I can make a PR if you think this is a good idea.

**Comment by igrishaev** [comment]
My bad, I grabbed `deep-merge` from somewhere without testing it carefully. It would be great if you give me a hand with that.

**Comment by igrishaev** [comment]
As far a I remember, leiningen carries good merging utilities.

**Comment by AdamFrey** [comment]
ok, I will try to get a PR for you this week

**Comment by igrishaev** [comment]
@AdamFrey your fix has been deployed to Clojars, please update to 0.1.8.
