### ISSUE TITLE
fix todo when passing env

### ISSUE THREAD

**Issue by igrishaev** [igrishaev/etaoin#43]
Функции для запуска драйвера принимают словарь переменных `:env` для процесса драйвера. Проблема в том, что при явной передаче переменных не учитываются текущие переменные. Поэтому надо не просто передавать их в ProcessBuilder, а сначала взять текущие через System/getenv и дополнить результат теми, что передали в :env, и только потом передать в билдер.

Можно взять способ как в книжке: прочитать переменные, перевести их в кложурную мапу, потом сделать merge. Кложурные мапы имплементят интерфейс Map, поэтому их можно передать как есть. Но ключи обязательно должны быть строками (и значения тоже). Кейворды в ключах перевести через name, а значения через str.

Убрать todo возле env в коде. Добавить в readme.

**Comment by Uunnamed** [comment]
`System/getenv` без значения, вернет весь список переменных среды, но я так понимаю это не то, что нам нужно. Т.е нужно либо задать переменные явно и их читать, либо фильтровать их по какому-то шаблону, верно?

**Comment by igrishaev** [comment]
дело в том, как ведет себя ProcessBuilder. Если не передать ему окружение, то он возьмет текущее. А если если что-то передать, от он получит только эти переменные, а текущие пропадут. Это не совсем то, что мы ожидаем, потому что обычно мы хотим передать несколько переменных вдобавок к текущим. Поэтому нужно взять текущее окружение и дополнить тем, что передали в драйвер в ключе env, и результат подать в process builder. Если ключ env пустой, то ничего не делать.
