### ISSUE TITLE
Add a way to return multiple elements from a query

### ISSUE THREAD

**Issue by AdamFrey** [igrishaev/etaoin#5]
Currently the `query` function only returns the first matching element from the browser. It seems important to also include a way to return all of the matching elments, similar to `findElements` in Selenium: 
(https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/WebElement.html#findElements-org.openqa.selenium.By-)

**Comment by igrishaev** [comment]
Done. I added `query-all` and other functions that end with `-el` to work with native elements. See code sample in `readme.md` and unit tests.

**Comment by AdamFrey** [comment]
Thanks for the great work!
