### ISSUE TITLE
How to upload file using etaoin?

### ISSUE THREAD

**Issue by abhi18av** [igrishaev/etaoin#52]
Hi @igrishaev 

I was trying out this library ( thanks for this pure clojure solution btw 👍  ) and to evaluate it, I wanted to translate [this tutorial](https://www.guru99.com/upload-download-file-selenium-webdriver.html) which relies on `selenium`

```clojure
(ns ui-test.file-upload
  (:use etaoin.api)
  (:require [clojure.test :as test]
            [etaoin.keys :as k]))

(def driver (chrome)) ;; here, a Firefox window should appear

;; let's perform a quick Wiki session
(go driver "http://demo.guru99.com/selenium/upload/")



(click driver {:id "terms" })



(click driver {:id "uploadfile_0" })



(fill {:id "uploadfile_0" } "")

(fill driver {:id "uploadfile_0"} )

```

I'm new to browser automation and clojure, could you help me out a bit please :)

**Comment by abhi18av** [comment]
Oh, I think I got it now 

```clojure 


(fill driver {:id "uploadfile_0"} "/Users/eklavya/Desktop/profile.jpg")



```

- is the magical command.

**Comment by igrishaev** [comment]
Hi @abhi18av,

yes, there is the SO answer to that.

I'll open that issue to create a shortcut for `upload_file`

**Comment by abhi18av** [comment]
Thanks, that'd be really user-friendly especially for beginners.

**Comment by igrishaev** [comment]
@abhi18av done, see `upload-file` in master or fresh snapshot

**Comment by abhi18av** [comment]
Wow! This was fast @igrishaev . I really appreciate it :+1:
