### ISSUE TITLE
Interacting with select controls

### ISSUE THREAD

**Issue by idevai** [igrishaev/etaoin#55]
What's the officially recommended way of doing this? I'd like to select a particular value from a HTML select element. As first try I could do this with first clicking the select and the clicking the option, however, my controls are not working the same way when it happens with human interaction (seemingly some javascript events are not fired properly?!)

**Comment by komcrad** [comment]
I'd look at the Select object in selenium and see how they handle it. I think it's part of the webdriver protocol. I don't believe they use any javascript shenanigans to accomplish the task.

**Comment by idevai** [comment]
I've looked into their sources, what they do is simply a click on the option (without first clicking the select). I've modified my test, but it's still the same. What I also observe is that seemingly the onClick handler gets called, but not the onInput. With human interaction in the browser, both onClick and onInput gets called.

**Comment by komcrad** [comment]
I don't think it's a bad option. Once again, you are probably wanting to not test the html elment itself.

**Comment by idevai** [comment]
Ah found the issue. Actually onInput is not valid in case of a select element, only for input type of elements. Changing to the onChange event works both for Webdriver and human interaction. Thank you.

**Comment by igrishaev** [comment]
@idevai well, it depends on what HTML structure do you have.

Sometimes, select widgets are implemented manually with lots of nested divs. In that case, you need to click on select, wait for a short time, then click on an element appeared in dropdown next.

When dealing with native select fields, you may send them proper keys. The standard `(fill...)` function should work. Most of modern browsers select proper option when you type something focusing on the main select field. Or you may click on select, wait for a bit and then click on `<option>` element.

**Comment by rgscherf** [comment]
@igrishaev Both (click...) and (fill...) work great for selecting single <option> elements. Is there a way to select more than one <option> at a time, though? E.g. as if ctrl-clicking another element?

**Comment by igrishaev** [comment]
@rgscherf right. Currently, I'm looking through actions in the Webdriver spec. Once I add them, there might be some high-level wrappers for custom action combos.
