### ISSUE TITLE
Add driver version support

### ISSUE THREAD

**Issue by igrishaev** [igrishaev/etaoin#59]
Когда-то у меня была мысль сделать поддержку разных версий драйверов в библиотеке, но я не осилил. Может, получится сейчас? Но сначала нужно подумать, нужно ли нам это вообще.

Идея в следующем: есть наша библотека и драйвер X. Со временем драйвер обновляется, что что-то перестает работать. Мы исправляем код под новый драйвер и выпускаем релиз. Тому, кто пожаловался, говорим -- скачайте новый брайвер и обновите библиотеку.

Так нормально, но было бы круто, если ли бы библиотка помнила прошлые реализации. Например, до версии драйвера 1.3 было так, а позже стало эдак. Тогда библиотеке не обящательно нужны свежие драйверы.

Для этого нужно, чтобы при старте мы определяли версию драйвера, например, 1.25. Это можно сделать, вызвав драйвер с ключом `--version`. Далее мы ханим версию словаре.

**Comment by igrishaev** [comment]
Теперь предположим, что у нас есть список версий этого драйвера, в которых что-то ломается, например

```
1.0
1.2
1.35
```

Если текущая версия 1.25, это значит, что последняя версия из списка -- 1.2 (самая близкая по меньшинству, но не превышающая ее).

**Comment by igrishaev** [comment]
Теперь представим, что driver-dispatch учитывает не только тип драйвера, но и версию:

```
(defmethod ... [:geckodriver :1.2] ...)

(defmethod [:geckodriver :1.35])
````

**Comment by igrishaev** [comment]
Тогда бы мы смогли добавить разные версии апих в зависимости от версии, и людям не придется обновлять драйверы.

**Comment by igrishaev** [comment]
Диспатч можно сделать хитрым: если текущая версия драйвера опережает последнюю из списка, мы считаем, что имеем дело с самой свежей версией драйвера. Например, у нас список

```
[1.1, 1.2, 1.5]
```

а у текущего драйвера версия 1.8. Значит, мы имеем дело с последней измветной нам версией. Диспатч вернет просто типа драйвера, например `:chrome.

Но на другой машине старый драйвер версии 1.4.234235. Ближайшая к нему версия, которую мы поддерживаем -- 1.2. Тогда диспатч вернет вектор `[:chrome "1.2"]`. Предположим, в этой версии по-другому работает клик на элемент. Тогда расширим мультиметод вектором:

```
(defmethod click ... [:chrome "1.2"]
   ... другая реалищация)
```

**Comment by igrishaev** [comment]
Еще нужно учесть откат к реализации по умлочанию. Предположим, переход по ссылке работает во всех версиях одинаково. Чтобы диспатч `[:chrome "1.2"]` сходился к `:chrome`, можно ввести локальную иерархию. Версия 1.5 имеет приоритет над 1.2, а 1.2 над 1.1 и так далее. Если реализации для версии нет, должна быть ее реализация по умолчанию (пустая версия).

**Comment by igrishaev** [comment]
Теперь вопросы:

- нужно ли нам это вообще?
- как часто ломаются апи в драйверах?
- насколько геморройно будет это реализовать, не станет ли код месивом?

**Comment by Uunnamed** [comment]
> Теперь вопросы:
> 
> * нужно ли нам это вообще?
> * как часто ломаются апи в драйверах?
> * насколько геморройно будет это реализовать, не станет ли код месивом?

начну с конца
на данный момент все драйверы перешли на стандарт w3c.
у нас в апи используются desiredCapabilities, для совместимости со старым json wire protocol. по факту ff проглатывает эту опцию, но работает по w3c, chrome и phantom работают по jwp, сафари только по w3c из-за чего пришлось в ручную делать затычку, если помнишь.
отличие jwp от w3c в конечных точках и иногда параметрах которые они принимают.
еще в jwp есть ендпоинты типо double-click, up, down, scroll и тп которые нужно придумывать как эмулировать.
у нас есть методы которые на них завязаны.
в сухом остатке сейчас у нас api состоит из смеси 2-х протоколов, вопрос только в вендорах, откажутся ли они поддерживать старый протокол или нет, от этого зависит сломается наше апи или нет, мне видится что нужно перевести все на w3c, чтобы в будущем не страдать, а jwp оставить только для фантома. но чтобы перевести, ножно понять для начала, нужно понять как сэмулировать методы, которые завязаны на jwp и которых нет на прямую в w3c. но селены я так понял отказались полностью от jwp и 4-я версия теперь только на w3c.

**Comment by igrishaev** [comment]
Еще вариант, сделать какое-то гибкое наследование, например `:safari`, `:safari-1.2`, `:safari-1.29.423`, но не факт, что мультиметод так умеет.

**Comment by igrishaev** [comment]
В общем, задача в том, чтобы исследовать, можно ли добавить это малыми усилиями, не переписывая весь код.

**Comment by igrishaev** [comment]
слишком сложно и абстрактно, пока уберу
