### ISSUE TITLE
Support for dealing with frames?

### ISSUE THREAD

**Issue by alsfreitaz** [igrishaev/etaoin#71]
Hi, @igrishaev. Do you have any plans for dealing with frames in the near future?

In my opinion, having a way of switching between frames and the default content is a major concern in many use cases and would not require so much effort.

By the way, great API. Simple but effective (as it should be). :)

**Comment by igrishaev** [comment]
Hi! In our project, we do not have iframes at all, so that's why I never thought of them. But you are right, those api should be implemented. I hope I'll deal with them soon.

**Comment by igrishaev** [comment]
Done in 0.2.2. Will update the readme with examples soon.
