### ISSUE TITLE
Cannot run program "geckodriver": error=2

### ISSUE THREAD

**Issue by olegakbarov** [igrishaev/etaoin#76]
Do i have to perform some more specific installation instructions apart from stated readme?

macOS High Sierra 10.13.2
Clojure 1.8.0 (also tested with 1.9.0)
Lein 2.8.1
Java 1.8.0_152
Firefox 57.0.1 (64-bit)

```
user=> (def driver (firefox))
CompilerException java.io.IOException: Cannot run program "geckodriver": error=2, No such file or directory, compiling:(form-init5225895260376245612.clj:1:13)
```

Same with Chrome:
```
user=> (def driver (chrome))
CompilerException java.io.IOException: Cannot run program "chromedriver": error=2, No such file or directory, compiling:(form-init5225895260376245612.clj:1:13)
```

**Comment by sogaiu** [comment]
I encountered a similar error.

The following was helpful here:

https://gist.github.com/cgoldberg/4097efbfeb40adf698a7d05e75e0ff51

**Comment by sogaiu** [comment]
Ah, it looks like there are instructions further down:

https://github.com/igrishaev/etaoin#installing-drivers

**Comment by igrishaev** [comment]
Hi guys, it seems the library cannot find the driver installed on your machines.

Here is a paragraph from readme:

> Now, check your installation launching any of these commands. For each command, an endless process with a local HTTP server should start.

```
chromedriver
geckodriver
phantomjs --wd
safaridriver -p 0
```

If some of the commands does not work, you should either:

1. Add path to the driver's binary file into PATH variable;
2. put a symlink for the binary file into /usr/bin or some other system library;
3. specify path to the binary file when creating a driver instance:

`(def driver (chrome {:path-driver "/path/to/driver/binary"}))`

**Comment by igrishaev** [comment]
closing since it's not a library issue.
