### ISSUE TITLE
Support selecyByVisibleText

### ISSUE THREAD

**Issue by SevereOverfl0w** [igrishaev/etaoin#85]
This is useful for working with dropdowns!

http://webdriver.io/api/action/selectByVisibleText.html

**Comment by igrishaev** [comment]
@Uunnamed maybe the function's name might be different, but we still need a function to select an option. People often ask about that. Needs to be discussed.

**Comment by Uunnamed** [comment]
Hi @SevereOverfl0w 

Since etaoin 0.3.8 for this purpose available function `select`
``` 
(defn select
  "Select element in select-box by visible text on click.

  Arguments:

  - `driver`: a driver instance,

  - `q`: a query term, see `query` function for more info,

  - `text`: a string, text in the option you want to select"
  [driver q text]
  (let [el (query driver q {:tag :option :fn/has-text text})]
    (click-el driver el))) 
```
