### ISSUE TITLE
provide examples for querying elements in readme

### ISSUE THREAD

**Issue by igrishaev** [igrishaev/etaoin#92]

**Comment by JulesGosnell** [comment]
I want to return a list of rows from a dom for further analysis in Clojure.

I followed your doc.

I run : 

(query driver ".//table[@class='raise_list']/tbody/tr/td/span/a[text()='Suspend']")

I get back:

"0.10521287632248977-8"

What does this mean ?
Where are my rows :-( ?
Why is there only one value returned - my expression should have matched many.

[etaoin "0.2.8-SNAPSHOT"]
[cheshire "5.8.0"]

ChromeDriver 2.38.552518 (183d19265345f54ce39cbb94cf81ba5f15905011)

Thanks for all your work on this - it looks like it might be just what I am looking for, if I can figure out how to return multiple elements....

Jules

**Comment by JulesGosnell** [comment]
looks like the doc needs an update - "find all the disabled input widgets:" example is using query - not query-all.

Will try query-all and see what I get

**Comment by igrishaev** [comment]
@Uunnamed could you please put some examples here and in the readme (if we miss them)?

**Comment by Uunnamed** [comment]
Hi @JulesGosnell 
> What does this mean ?.

This is an element ID that can be used in functions like `file-el`, `click-el` ...etc.

>  `Where are my rows :-( ?

Using the received IDs you can continue exploring the dom using functions starting from [here](http://etaoin.grishaev.me/etaoin.api.html#var-get-element-attr). Or use the `get-source` function to get the entire page code and parse the rows using other libraries.

> Why is there only one value returned - my expression should have matched many.

To get all matching elements, use the 'query-all' function and look at the `query-true`function perhaps it will also be useful to you.

Thank you for your feedback.
