### ISSUE TITLE
Is create-session thread safe?

### ISSUE THREAD

**Issue by Atsman** [igrishaev/etaoin#99]
Hi, i want to use one instance of chrome and create multiple session, to use them from different threads. Is it possible? 

My tests shows that no. Because i see errors about elements that are not attached to document.
So is it true, that the only way is to create multiple (chrome) instances? :(

**Comment by Atsman** [comment]
Is it possible to return new driver instance on new-session? So that it will work only with it's own session? That how puppeteer do it. You create multiple page object and can interact concurrently with them.

**Comment by igrishaev** [comment]
Hi @Atsman, that should be tested. I remember, maybe Chrome supports multiple sessions, but not Firefox. But it does not matter since every `(chrome)` or `(firefox)` call starts a new process which are completely separated from each other.
